/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSObject.h>

@class NSString;
@protocol NSURLAuthenticationChallengeSender;

@interface ISAuthenticationChallenge : NSObject {
	NSString* _localizedMessage;
	NSString* _localizedTitle;
}
@property(readonly, assign) id<NSURLAuthenticationChallengeSender> sender;
@property(readonly, assign) BOOL userNameIsEmail;
@property(readonly, assign) BOOL userNameIsEditable;
@property(readonly, assign) int failureCount;
@property(readonly, assign) NSString* user;
@property(readonly, assign) NSString* password;
@property(readonly, assign) BOOL hasPassword;
@property(retain) NSString* localizedTitle;
@property(retain) NSString* localizedMessage;
-(void)dealloc;
-(void)cancelAuthentication;
-(void)useCredential:(id)credential;
@end

