/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISDialogOperation.h"

@class ISAuthenticationChallenge;

@interface ISAuthenticationChallengeOperation : ISDialogOperation {
	ISAuthenticationChallenge* _challenge;
}
@property(retain) ISAuthenticationChallenge* challenge;
+(id)operationWithChallenge:(id)challenge;
-(void)dealloc;
-(id)_copyCredentialForSignInResponseDictionary:(id)responseDictionary;
-(void)handleButtonSelected:(int)selected withResponseDictionary:(id)responseDictionary;
-(void)run;
@end

