/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSObject.h>
#import "iTunesStore-Structs.h"


@interface ISCertificate : NSObject {
	SecTrust* _trust;
}
-(void)dealloc;
-(void)setCertificateData:(id)data;
-(BOOL)checkData:(id)data againstAppleSignature:(id)signature;
-(BOOL)checkData:(id)data againstSignature:(id)signature;
-(void)_invalidate;
-(BOOL)isValid;
@end

