/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISSingleton.h"
#import "iTunesStore-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

@interface ISDevice : NSObject <ISSingleton> {
	unsigned _daemonLaunchCount;
	dispatch_queue_s* _dispatchQueue;
	NSString* _guid;
	NSString* _hardwareModel;
	BOOL _pluggedIn;
	int _pluggedInToken;
	NSString* _productVersion;
	int _type;
}
@property(readonly, assign) int type;
@property(readonly, assign) NSString* systemName;
@property(readonly, assign) NSString* serialNumber;
@property(readonly, assign) NSString* productVersion;
@property(readonly, assign) NSString* hardwareName;
@property(readonly, assign) NSString* hardwareModel;
@property(readonly, assign) NSString* guid;
@property(readonly, assign) NSString* deviceName;
@property(readonly, assign, getter=isPluggedIn) BOOL pluggedIn;
+(id)sharedInstance;
+(void)setSharedInstance:(id)instance;
-(id)init;
-(void)dealloc;
-(BOOL)releasePowerAssertion:(id)assertion;
-(id)copyPurchaseValidationContext;
-(id)copyProtocolConditionalContext;
-(BOOL)checkCapabilities:(id)capabilities withMismatches:(id*)mismatches;
-(BOOL)hasCapability:(int)capability;
-(BOOL)isAnyWildcat;
-(id)supportedOfferDeviceForDevices:(id)devices;
-(void)daemonWillExitCleanly;
-(void)daemonDidLaunch;
-(unsigned)daemonLaunchCount;
-(BOOL)takePowerAssertion:(id)assertion;
-(int)_deviceTypeForModelString:(id)modelString;
-(BOOL)_releasePowerAssertion:(id)assertion;
-(void)_setPluggedIn:(BOOL)anIn;
-(id)_copyCapabilityValueForKey:(CFStringRef)key;
-(BOOL)_isPodcastCapable;
-(BOOL)_isHDVideoCapable;
-(void)_initDeviceType;
-(BOOL)isAnyIPhone;
-(BOOL)isAnyIPod;
-(void)_cancelScheduledPowerAssertionRelease:(id)release;
-(void)_schedulePowerAssertionRelease:(id)release;
@end

