/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISOperation.h"
#import "iTunesStore-Structs.h"

@class ISDialogButton, NSArray, ISDialog;
@protocol ISDialogOperationDelegate;

@interface ISDialogOperation : ISOperation {
	ISDialog* _dialog;
	BOOL _performDefaultActions;
	ISDialogButton* _selectedButton;
	NSArray* _textFieldValues;
	id _userNotification;
}
@property(retain) id userNotification;
@property(readonly, assign) NSArray* textFieldValues;
@property(retain) ISDialogButton* selectedButton;
@property(assign) BOOL performDefaultActions;
@property(retain) ISDialog* dialog;
@property(assign) id<ISDialogOperationDelegate> delegate;
+(id)operationWithError:(id)error;
+(id)operationWithDialog:(id)dialog;
-(void)cancel;
-(id)init;
-(void)dealloc;
-(void)_handleResponseForNotification:(CFUserNotificationRef)notification responseFlags:(unsigned long)flags;
-(void)_waitForUserNotificationResponse:(CFUserNotificationRef)userNotificationResponse;
-(void)_showUserNotification:(id)notification;
-(void)handleButtonSelected:(int)selected withResponseDictionary:(id)responseDictionary;
-(void)run;
-(void)_run;
@end

