/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSObject.h>

@class NSLock, NSArray, NSString, NSMutableDictionary, SSAuthenticationContext;

@interface ISDialog : NSObject {
	BOOL _allowDuplicates;
	SSAuthenticationContext* _authenticationContext;
	BOOL _authorizationIsForced;
	NSArray* _buttons;
	int _defaultButtonIndex;
	NSString* _displayCountKey;
	BOOL _dismissOnLock;
	BOOL _expectsResponse;
	BOOL _groupsTextFields;
	int _kind;
	NSLock* _lock;
	int _maxDisplayCount;
	NSString* _message;
	BOOL _oneButtonPerLine;
	BOOL _shouldDismissAfterUnlock;
	BOOL _shouldDisplayAsTopMost;
	BOOL _shouldHideButtonsInAwayView;
	NSArray* _textFields;
	NSString* _title;
	int _unlockActionButtonIndex;
	NSMutableDictionary* _userInfo;
}
@property(readonly, assign, getter=isDisplayable) BOOL displayable;
@property(assign) int maximumDisplayCount;
@property(copy) NSString* displayCountKey;
@property(copy) SSAuthenticationContext* authenticationContext;
@property(assign) int kind;
@property(assign) BOOL shouldHideButtonsInAwayView;
@property(assign) BOOL shouldDisplayAsTopMost;
@property(assign) BOOL shouldDismissAfterUnlock;
@property(assign) BOOL expectsResponse;
@property(assign) BOOL dismissOnLock;
@property(assign) BOOL authorizationIsForced;
@property(assign) BOOL allowDuplicates;
@property(retain) NSString* title;
@property(retain) NSString* message;
@property(retain) NSArray* textFields;
@property(assign) BOOL groupsTextFields;
@property(assign) int unlockActionButtonIndex;
@property(assign) BOOL oneButtonPerLine;
@property(assign) int defaultButtonIndex;
@property(retain) NSArray* buttons;
+(int)displayCountForKey:(id)key;
-(BOOL)isEqual:(id)equal;
-(id)init;
-(void)dealloc;
-(id)initWithOfferDeviceError:(id)offerDeviceError;
-(void)incrementDisplayCount;
-(id)initWithError:(id)error;
-(id)initWithDialogDictionary:(id)dialogDictionary;
-(id)initWithTitle:(id)title message:(id)message;
-(id)valueForUserInfoKey:(id)userInfoKey;
-(void)setValue:(id)value forUserInfoKey:(id)userInfoKey;
-(int)_kindForString:(id)string;
-(id)initWithAuthenticationChallege:(id)authenticationChallege;
-(id)copyUserNotification;
@end

