/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface ISDialogButton : NSObject {
	int _actionType;
	id _parameter;
	NSString* _title;
	int _urlType;
}
@property(assign) int urlType;
@property(retain) NSString* title;
@property(retain) id parameter;
@property(assign) int actionType;
+(id)buttonWithTitle:(id)title;
-(void)dealloc;
-(void)loadFromDictionary:(id)dictionary;
-(void)_openURLWithRequest:(id)request;
-(id)_accountURLForURL:(id)url authenticationContext:(id)context;
-(int)_urlTypeForString:(id)string;
-(int)_actionTypeForString:(id)string;
-(BOOL)isEqual:(id)equal superficial:(BOOL)superficial;
-(void)setActionTypeWithString:(id)string;
-(void)performDefaultActionForDialog:(id)dialog;
@end

