/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISOperation.h"

@class ISReview, NSURL;

@interface ISFetchReviewOperation : ISOperation {
	int _assetType;
	BOOL _backgroundReview;
	unsigned long long _itemIdentifier;
	unsigned _softwareVersionIdentifier;
	ISReview* _review;
	NSURL* _url;
}
@property(retain) ISReview* review;
@property(assign, getter=isBackgroundReview) BOOL backgroundReview;
@property(retain) NSURL* url;
@property(assign) unsigned long long itemIdentifier;
@property(assign) unsigned softwareVersionIdentifier;
@property(assign) int assetType;
-(void)dealloc;
-(void)_fetchReviewInformation;
-(void)run;
@end

