/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISSingleton.h"
#import <Foundation/NSObject.h>


@interface ISITunesSyncHelper : NSObject <ISSingleton> {
}
+(id)sharedInstance;
+(void)setSharedInstance:(id)instance;
@end

