/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISOperation.h"
#import "ISStoreURLOperationDelegate.h"

@class SSURLBagContext;

@interface ISLoadURLBagOperation : ISOperation <ISStoreURLOperationDelegate> {
	SSURLBagContext* _context;
}
@property(readonly, assign) SSURLBagContext* context;
-(id)init;
-(void)dealloc;
-(BOOL)operation:(id)operation shouldSetStoreFrontID:(id)anId;
-(void)operation:(id)operation willSendRequest:(id)request;
-(void)operation:(id)operation finishedWithOutput:(id)output;
-(id)uniqueKey;
-(id)initWithBagContext:(id)bagContext;
-(void)_addHeadersToRequestProperties:(id)requestProperties;
-(id)_copyProductionBootstrapURLs;
-(id)_copySandboxBootstrapURLs;
-(void)_loadConfigurationFromURLBag:(id)urlbag;
-(void)_loadURLBagFromURL:(id)url;
-(id)_copyBootstrapURLs;
-(void)run;
@end

