/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "iTunesStore-Structs.h"
#import "ISSingleton.h"
#import <Foundation/NSObject.h>
#import "SSDownloadQueueObserver.h"

@class NSMutableSet, NSString;

@interface ISNetworkObserver : NSObject <ISSingleton, SSDownloadQueueObserver> {
	dispatch_queue_s* _dispatchQueue;
	BOOL _isCellularRestricted;
	double _lastNetworkTypeChangeTime;
	int _networkUsageCount;
	int _networkType;
	NSMutableSet* _observedDownloadQueues;
	SCNetworkReachabilityRef _reachability;
}
@property(readonly, assign, getter=isWiFiEnabled) BOOL wifiEnabled;
@property(readonly, assign) NSString* connectionTypeHeader;
@property(readonly, assign) BOOL shouldShowCellularAutomaticDownloadsSwitch;
@property(readonly, assign, getter=isCellularDataRestricted) BOOL cellularDataRestricted;
@property(readonly, assign, getter=isUsingNetwork) BOOL usingNetwork;
@property(readonly, assign) double lastNetworkTypeChangeTime;
@property(assign) int networkType;
+(id)sharedInstance;
+(void)setSharedInstance:(id)instance;
+(void)setWiFiEnabled:(BOOL)enabled;
+(void)setAirplaneModeEnabled:(BOOL)enabled;
+(void)set3GEnabled:(BOOL)enabled;
-(id)init;
-(void)dealloc;
-(void)reloadNetworkType;
-(void)endUsingNetwork;
-(void)beginUsingNetwork;
-(void)downloadQueue:(id)queue changedWithRemovals:(id)removals;
-(void)downloadQueueNetworkUsageChanged:(id)changed;
-(void)_reloadCellularRestriction;
-(void)endObservingDownloadQueue:(id)queue;
-(void)beginObservingDownloadQueue:(id)queue;
-(int)_networkTypeFromDataIndicator:(id)dataIndicator;
-(void)_postTypeChangedNotificationFromValue:(int)value toValue:(int)value2;
-(int)_setNetworkType:(int)type;
-(void)_reloadNetworkType;
-(id)copyValueForCarrierBundleKey:(id)carrierBundleKey;
-(void)_postUsageChangedToValue:(BOOL)value;
-(BOOL)_ntsIsUsingNetwork;
-(void)_telephonyObserverAvailableNotification:(id)notification;
-(void)_dataStatusChangedNotification:(id)notification;
-(int)_currentNetworkType;
@end

