/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISOperation.h"

@class ISOpenURLRequest;

@interface ISOpenURLOperation : ISOperation {
@private
	ISOpenURLRequest* _request;
}
@property(readonly, assign) ISOpenURLRequest* openURLRequest;
-(id)init;
-(void)dealloc;
-(id)initWithOpenURLRequest:(id)openURLRequest;
-(id)_newSortedTargetsArray;
-(BOOL)_openURL:(id)url;
-(void)run;
@end

