/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSOperation.h>

@class NSError, NSLock, NSRunLoop, SSOperationProgress, NSArray, NSString;
@protocol ISOperationDelegate;

@interface ISOperation : NSOperation {
	id<ISOperationDelegate> _delegate;
	NSError* _error;
	NSLock* _lock;
	NSRunLoop* _operationRunLoop;
	ISOperation* _parentOperation;
	SSOperationProgress* _progress;
	BOOL _shouldMessageMainThread;
	NSString* _powerAssertionIdentifier;
	ISOperation* _subOperation;
	NSArray* _serializationLockIdentifiers;
	BOOL _shouldRunWithBackgroundPriority;
	BOOL _success;
	id _threadSafeDelegate;
}
@property(retain) ISOperation* subOperation;
@property(copy) NSArray* serializationLockIdentifiers;
@property(readonly, assign) id threadSafeDelegate;
@property(retain) NSRunLoop* operationRunLoop;
@property(readonly, assign, nonatomic) SSOperationProgress* progress;
@property(retain) ISOperation* parentOperation;
@property(readonly, assign) int progressWeight;
@property(assign) BOOL success;
@property(retain) NSError* error;
@property(assign) BOOL shouldRunWithBackgroundPriority;
@property(readonly, assign) NSString* uniqueKey;
@property(retain) NSString* powerAssertionIdentifier;
@property(assign) BOOL shouldMessageMainThread;
@property(assign) id<ISOperationDelegate> delegate;
-(void)main;
-(void)cancel;
-(id)init;
-(void)dealloc;
-(void)sendProgressToDelegate;
-(long)runRunLoopUntilStopped;
-(void)stopRunLoop;
-(void)_sendSuccessToDelegate;
-(BOOL)runSubOperation:(id)operation returningError:(id*)error;
-(BOOL)loadURLBagWithContext:(id)context returningError:(id*)error;
-(id)authenticatedAccountDSID;
-(void)_sendErrorToDelegate:(id)delegate;
-(BOOL)loadSoftwareMapReturningError:(id*)error;
-(BOOL)copyAccountID:(id*)anId byAuthenticatingWithContext:(id)context returningError:(id*)error;
-(id)copySerializationLocks;
-(BOOL)runSubOperation:(id)operation onQueue:(id)queue error:(id*)error;
-(void)run:(BOOL)run;
-(void)_sendWillStartToDelegate;
-(id)copyActivePowerAssertionIdentifiers;
-(void)_failAfterException;
-(void)_main:(BOOL)main;
-(BOOL)shouldFailAfterUniquePredecessorError:(id)error;
-(void)_dispatchCompletionBlock;
-(void)run;
-(void)unlock;
-(void)lock;
@end

