/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSObject.h>
#import "NSCopying.h"
#import "iTunesStore-Structs.h"

@class NSArray, NSMutableDictionary, NSNumber;

@interface ISPersonalizeOffersRequest : NSObject <NSCopying> {
@private
	NSNumber* _accountIdentifier;
	NSMutableDictionary* _itemIDsByType;
}
@property(readonly, assign, nonatomic) NSArray* allItemTypes;
@property(retain, nonatomic) NSNumber* accountIdentifier;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(void)addItemIdentifier:(id)identifier forItemType:(id)itemType;
-(id)itemIdentifiersForItemType:(id)itemType;
-(id)initWithItems:(id)items;
@end

