/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISOperation.h"
#import "ISStoreURLOperationDelegate.h"

@class ISReview;

@interface ISPostReviewOperation : ISOperation <ISStoreURLOperationDelegate> {
	BOOL _backgroundReview;
	ISReview* _review;
}
@property(retain) ISReview* review;
@property(assign, getter=isBackgroundReview) BOOL backgroundReview;
-(void)dealloc;
-(void)operation:(id)operation finishedWithOutput:(id)output;
-(id)_httpBody;
-(void)run;
@end

