/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "NSCopying.h"
#import "ISDataProvider.h"
#import "iTunesStore-Structs.h"


@interface ISPropertyListProvider : ISDataProvider <NSCopying> {
	BOOL _shouldPostFooterSectionChanged;
	BOOL _shouldProcessAccount;
	BOOL _shouldProcessAuthenticationDialogs;
	BOOL _shouldProcessDialogs;
	BOOL _shouldProcessProtocol;
	BOOL _shouldTriggerDownloads;
}
@property(assign) BOOL shouldTriggerDownloads;
@property(assign) BOOL shouldProcessProtocol;
@property(assign) BOOL shouldProcessDialogs;
@property(assign) BOOL shouldProcessAuthenticationDialogs;
@property(assign) BOOL shouldProcessAccount;
@property(assign) BOOL shouldPostFooterSectionChanged;
-(id)copyWithZone:(NSZone*)zone;
-(id)init;
-(BOOL)parseData:(id)data returningError:(id*)error;
-(void)_selectFooterSection:(id)section;
-(void)_checkDownloadQueues;
-(BOOL)processPropertyList:(id)list returningError:(id*)error;
-(BOOL)_processFailureTypeFromPropertyList:(id)propertyList error:(id*)error;
-(void)_performActionsForResponse:(id)response;
-(BOOL)processDialogFromPropertyList:(id)propertyList returningError:(id*)error;
-(BOOL)_runAuthorizationDialog:(id)dialog returningError:(id*)error;
@end

