/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "NSCopying.h"
#import "ISDataProvider.h"
#import "iTunesStore-Structs.h"


@interface ISReviewProvider : ISDataProvider <NSCopying> {
	BOOL _backgroundReview;
}
@property(assign, getter=isBackgroundReview) BOOL backgroundReview;
-(id)copyWithZone:(NSZone*)zone;
-(BOOL)parseData:(id)data returningError:(id*)error;
@end

