/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "NSCoding.h"
#import <Foundation/NSObject.h>
#import "NSCopying.h"
#import "iTunesStore-Structs.h"

@class NSURL, NSString;

@interface ISReview : NSObject <NSCoding, NSCopying> {
	int _assetType;
	NSString* _body;
	unsigned _bodyMaxLength;
	NSURL* _infoURL;
	unsigned long long _itemIdentifier;
	NSString* _nickname;
	BOOL _nicknameIsConfirmed;
	unsigned _nicknameMaxLength;
	float _rating;
	NSURL* _submitURL;
	NSString* _title;
	unsigned _titleMaxLength;
}
@property(assign, nonatomic) unsigned titleMaxLength;
@property(assign, nonatomic) unsigned nicknameMaxLength;
@property(assign, nonatomic) BOOL nicknameIsConfirmed;
@property(assign, nonatomic) unsigned bodyMaxLength;
@property(retain, nonatomic) NSURL* submitURL;
@property(retain, nonatomic) NSURL* infoURL;
@property(assign, nonatomic) unsigned long long itemIdentifier;
@property(assign, nonatomic) int assetType;
@property(retain, nonatomic) NSString* title;
@property(assign, nonatomic) float rating;
@property(retain, nonatomic) NSString* nickname;
@property(retain, nonatomic) NSString* body;
@property(readonly, assign, nonatomic) BOOL hasSavedDraft;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(void)mergeWithReview:(id)review preferLocalValues:(BOOL)values;
-(BOOL)removeDraft;
-(BOOL)restoreFromDraft;
-(BOOL)saveAsDraft;
-(void)loadFromDictionary:(id)dictionary;
-(id)_draftFileName;
-(id)_draftsDirectoryPath;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
@end

