/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISOperation.h"

@class NSURL, NSNumber, SSAuthenticationContext, ISDialog;

@interface ISServerAuthenticationOperation : ISOperation {
	NSNumber* _authenticatedAccountDSID;
	SSAuthenticationContext* _authenticationContext;
	ISDialog* _dialog;
	NSURL* _redirectURL;
}
@property(retain) NSURL* redirectURL;
@property(retain) NSNumber* authenticatedAccountDSID;
@property(retain) ISDialog* dialog;
@property(retain) SSAuthenticationContext* authenticationContext;
-(void)dealloc;
-(BOOL)_handleSelectedButton:(id)button;
-(BOOL)_copyAccountIdentifier:(id*)identifier returningError:(id*)error;
-(BOOL)_shouldAuthenticateForButton:(id)button;
-(BOOL)_copySelectedButton:(id*)button returningError:(id*)error;
-(id)_copyButtonForDialogSkip;
-(id)_copyAuthenticationContext;
-(void)run;
@end

