/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISOperation.h"

@class NSString;

@interface ISSetApplicationBadgeOperation : ISOperation {
	id _badgeValue;
	NSString* _bundleIdentifier;
}
@property(retain) NSString* bundleIdentifier;
@property(retain) id badgeValue;
-(void)dealloc;
-(id)uniqueKey;
-(void)run;
@end

