/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSObject.h>
#import "iTunesStore-Structs.h"

@class NSArray;

@interface ISSoftwareMap : NSObject {
	NSArray* _applications;
}
@property(readonly, assign, nonatomic) NSArray* applications;
+(id)applicationForBundleIdentifier:(id)bundleIdentifier;
+(void)invalidateCurrentMap;
+(void)startObservingNotifications;
+(id)loadedMap;
+(void)_startWatchingInstallationNotifications;
+(BOOL)haveApplicationsOfType:(CFStringRef)type;
+(id)currentMap;
+(void)setCurrentMap:(id)map;
+(BOOL)currentMapIsValid;
+(id)applicationForBundleIdentifier:(id)bundleIdentifier applicationType:(CFStringRef)type;
-(id)init;
-(void)dealloc;
-(id)applicationForBundleIdentifier:(id)bundleIdentifier;
-(id)applicationForItemIdentifier:(id)itemIdentifier;
-(id)copySoftwareUpdatesPropertyList;
-(id)_newSoftwareUpdateDictionaryForApplication:(id)application;
-(id)_softwareUpdatesAccountsStringForApplications:(id)applications;
-(id)copySoftwareUpdatesPropertyListWithUpdatesContext:(id)updatesContext;
-(void)_loadFromMobileInstallation;
@end

