/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "SSXPCCoding.h"
#import <Foundation/NSObject.h>

@class SSItemContentRating, NSArray, NSString, NSNumber;

@interface ISSoftwareApplication : NSObject <SSXPCCoding> {
	NSNumber* _accountDSID;
	NSString* _accountIdentifier;
	NSString* _bundleIdentifier;
	NSString* _bundleShortVersionString;
	NSString* _bundleVersion;
	NSString* _containerPath;
	SSItemContentRating* _contentRating;
	NSNumber* _itemIdentifier;
	NSString* _softwareType;
	NSNumber* _storeFrontIdentifier;
	NSNumber* _versionIdentifier;
	NSArray* _versionOrdering;
}
@property(copy, nonatomic) NSArray* versionOrdering;
@property(retain, nonatomic) NSNumber* versionIdentifier;
@property(retain, nonatomic) NSNumber* storeFrontIdentifier;
@property(copy, nonatomic) NSString* softwareType;
@property(retain, nonatomic) NSNumber* itemIdentifier;
@property(copy, nonatomic) SSItemContentRating* contentRating;
@property(copy, nonatomic) NSString* containerPath;
@property(copy, nonatomic) NSString* bundleVersion;
@property(copy, nonatomic) NSString* bundleShortVersionString;
@property(copy, nonatomic) NSString* bundleIdentifier;
@property(copy, nonatomic) NSString* accountIdentifier;
@property(retain, nonatomic) NSNumber* accountDSID;
+(id)lookupAttributeKeys;
-(id)description;
-(void)dealloc;
-(id)initWithMobileInstallationDictionary:(id)mobileInstallationDictionary;
-(void*)copyXPCEncoding;
-(id)initWithXPCEncoding:(void*)xpcencoding;
-(void)_loadMetadataFromContainer:(id)container;
@end

