/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "iTunesStore-Structs.h"
#import <Foundation/NSObject.h>

@class NSDictionary, NSMutableSet;

@interface ISSpringBoardUtility : NSObject {
	dispatch_queue_s* _dispatchQueue;
	NSDictionary* _enabledRemoteNotificationTypes;
	NSMutableSet* _processAssertions;
}
@property(readonly, assign) BOOL hasProcessAssertions;
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(SBSProcessAssertionRef)takeProcessAssertionWithIdentifier:(id)identifier displayIdentifier:(id)identifier2 launchOptions:(id)options;
-(void)releaseProcessAssertion:(SBSProcessAssertionRef)assertion;
-(void)suspendFrontApplication;
-(void)setBadgeValue:(id)value forIdentifier:(id)identifier;
-(void)resetEnabledRemoteNotificationTypes;
-(void)removeDefaultPNGSnapshotsForIdentifier:(id)identifier;
-(int)enabledRemoteNotificationTypesForBundleIdentifier:(id)bundleIdentifier;
-(void)cancelDownloadingIconForPurchase:(id)purchase;
-(void)addDownloadingIconWithIdentifier:(id)identifier bundleIdentifier:(id)identifier2 softwareType:(id)type;
-(void)cancelDownloadingIconForIdentifier:(id)identifier;
@end

