/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "iTunesStore-Structs.h"
#import <Foundation/NSObject.h>


@interface ISSQLiteDatabase : NSObject {
	sqlite3* _db;
	BOOL _isInTransaction;
	dispatch_queue_s* _dispatchQueue;
	CFDictionaryRef _statementCache;
}
+(void)_stepStatement:(sqlite3_stmt*)statement hasRow:(BOOL*)row didFinish:(BOOL*)finish;
+(BOOL)statementDidFinishAfterStepping:(sqlite3_stmt*)statement;
+(BOOL)statementHasRowAfterStepping:(sqlite3_stmt*)stepping;
-(BOOL)executeSQL:(id)sql;
-(void)prepareStatementForSQL:(id)sql cache:(BOOL)cache usingBlock:(id)block;
-(void)performTransactionWithBlock:(id)block;
-(void)accessDatabaseUsingBlock:(id)block;
-(void)dealloc;
-(sqlite3_stmt*)_statementForSQL:(id)sql cache:(BOOL)cache;
-(void)_accessDatabaseUsingBlock:(id)block;
-(int)_resetAndReopenDatabaseWithPath:(id)path;
-(id)initWithDatabaseURL:(id)databaseURL;
@end

