/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISURLOperation.h"

@class NSNumber;
@protocol ISStoreURLOperationDelegate;

@interface ISStoreURLOperation : ISURLOperation {
	NSNumber* _authenticatedDSID;
	BOOL _canSendGUIDParameter;
	BOOL _needsAuthentication;
	BOOL _needsURLBag;
	BOOL _urlKnownToBeTrusted;
	BOOL _useUserSpecificURLBag;
}
@property(retain) NSNumber* authenticatedDSID;
@property(assign) BOOL useUserSpecificURLBag;
@property(assign) BOOL needsAuthentication;
@property(assign) BOOL urlKnownToBeTrusted;
@property(assign) BOOL needsURLBag;
@property(assign) BOOL canSendGUIDParameter;
@property(assign) id<ISStoreURLOperationDelegate> delegate;
+(void)addITunesStoreHeadersToRequest:(id)request;
+(void)handleITunesStoreResponseHeaders:(id)headers;
+(id)pingOperationWithUrl:(id)url;
+(id)propertyListOperationWithURLBagKey:(id)urlbagKey;
+(id)itemPingOperationWithIdentifier:(unsigned long long)identifier urlBagKey:(id)key;
+(id)_restrictionsHeaderValue;
+(void)_addITunesStoreHeadersToRequest:(id)request withBagContext:(id)bagContext;
-(id)init;
-(void)dealloc;
-(void)handleResponse:(id)response;
-(id)authenticatedAccountDSID;
-(void)_addStandardQueryParametersForURL:(id)url;
-(BOOL)_canSendTokenToURL:(id)url;
-(id)_urlFromURLBagForRequestProperties:(id)requestProperties inBagContext:(id)bagContext;
-(void)_runURLOperation;
-(BOOL)_authenticateReturningError:(id*)error;
-(id)_storeFrontIdentifier;
-(id)_account;
-(id)_copyURLBagContext;
-(BOOL)handleRedirectFromDataProvider:(id)dataProvider;
-(BOOL)shouldFollowRedirectWithRequest:(id)request returningError:(id*)error;
-(id)newRequestWithURL:(id)url;
-(id)_copyAuthenticationContext;
-(void)run;
@end

