/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISAuthenticationChallenge.h"

@class NSString;
@protocol NSURLAuthenticationChallengeSender;

@interface ISStoreAuthenticationChallenge : ISAuthenticationChallenge {
	int _failureCount;
	BOOL _hasPassword;
	NSString* _password;
	id<NSURLAuthenticationChallengeSender> _sender;
	NSString* _user;
	BOOL _userNameIsEditable;
}
@property(assign) BOOL userNameIsEditable;
@property(retain) NSString* user;
@property(assign) id<NSURLAuthenticationChallengeSender> sender;
@property(retain) NSString* password;
@property(assign) BOOL hasPassword;
@property(assign) int failureCount;
-(id)init;
-(void)dealloc;
-(BOOL)userNameIsEmail;
@end

