/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISSingleton.h"
#import "iTunesStore-Structs.h"
#import <Foundation/NSObject.h>

@class NSString, NSRecursiveLock;

@interface ISTelephonyObserver : NSObject <ISSingleton> {
	CTServerConnectionRef _connection;
	CFMachPortRef _connectionPort;
	CFRunLoopSourceRef _connectionRunLoopSource;
	NSString* _dataStatusIndicator;
	NSRecursiveLock* _lock;
	NSString* _operatorName;
	CFRunLoopRef _runLoop;
}
@property(readonly, assign) NSString* operatorName;
@property(readonly, assign) NSString* dataStatusIndicator;
+(id)sharedInstance;
+(void)setSharedInstance:(id)instance;
-(id)init;
-(void)dealloc;
-(BOOL)beginObservingOnRunLoop:(CFRunLoopRef)loop;
-(void)_handleServerInvalidated;
-(void)_handleNotificationWithName:(CFStringRef)name userInfo:(CFDictionaryRef)info;
-(void)_handleMessage:(void*)message withSize:(long)size;
-(BOOL)_establishServerConnection;
-(void)_invalidateServerConnection;
-(void)_registerForNotifications;
@end

