/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSMutableSet;

@interface ISUniqueOperationContext : NSObject {
	NSMutableSet* _operations;
	NSMutableDictionary* _uniqueOperations;
}
-(void)addOperation:(id)operation;
-(id)init;
-(void)dealloc;
-(BOOL)containsOperation:(id)operation;
-(void)setUniqueOperation:(id)operation forKey:(id)key;
-(id)uniqueOperationForKey:(id)key;
-(unsigned)countOfOperations;
-(void)removeOperation:(id)operation;
@end

