/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISOperationDelegate.h"


@protocol ISURLOperationDelegate <ISOperationDelegate>
@optional
-(id)operation:(id)operation sanitizedStringForString:(id)string;
-(BOOL)operation:(id)operation willSendRequestForAuthenticationChallenge:(id)authenticationChallenge;
-(void)operation:(id)operation willSendRequest:(id)request;
-(void)operation:(id)operation finishedWithOutput:(id)output;
-(void)operation:(id)operation didReceiveResponse:(id)response;
-(void)operation:(id)operation didDiscoverContentLength:(id)length;
@end

