/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISOperation.h"

@class ISURLOperation, NSMutableArray;

@interface ISURLOperationPoolOperation : ISOperation {
	int _cancelCount;
	BOOL _forwardImmediately;
	NSMutableArray* _operations;
}
@property(readonly, assign, nonatomic) ISURLOperation* mainOperation;
-(void)addOperation:(id)operation;
-(void)dealloc;
-(void)cancelOperation:(id)operation;
-(void)_forwardResponseFromOperation:(id)operation toOperation:(id)operation2;
-(BOOL)containsOperation:(id)operation;
-(void)run;
@end

