/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSObject.h>

@class NSDictionary, NSArray, SSURLBagContext, SSNetworkConstraints, NSSet;

@interface ISURLBag : NSObject {
	SSURLBagContext* _context;
	SSNetworkConstraints* _defaultConstraints;
	NSDictionary* _dictionary;
	NSArray* _guidPatterns;
	NSSet* _guidSchemes;
	NSDictionary* _headerPatterns;
	double _invalidationTime;
}
@property(readonly, assign, nonatomic, getter=isValid) BOOL valid;
@property(readonly, assign, nonatomic) NSDictionary* URLBagDictionary;
@property(copy, nonatomic) SSURLBagContext* URLBagContext;
@property(assign, nonatomic) double invalidationTime;
@property(readonly, assign) NSSet* availableStorefrontItemKinds;
+(id)storeFrontURLBagKeyForItemKind:(id)itemKind;
+(void)invalidateAllBags;
+(BOOL)urlIsTrusted:(id)trusted inBagContext:(id)bagContext;
+(id)urlForKey:(id)key inBagContext:(id)bagContext;
+(id)valueForKey:(id)key inBagContext:(id)bagContext;
+(id)urlBagForContext:(id)context;
+(BOOL)shouldSendGUIDForURL:(id)url inBagContext:(id)bagContext;
+(id)networkConstraintsForDownloadKind:(id)downloadKind inBagContext:(id)bagContext;
+(id)copyExtraHeadersForURL:(id)url inBagContext:(id)bagContext;
+(void)setURLBag:(id)bag forContext:(id)context;
+(id)_copyFallbackContextForContext:(id)context;
+(void)_loadItemKindURLBagKeyMap;
+(id)_urlBagForContext:(id)context;
-(id)init;
-(void)dealloc;
-(id)networkConstraintsForDownloadKind:(id)downloadKind;
-(id)searchQueryParametersForClientIdentifier:(id)clientIdentifier networkType:(int)type;
-(id)URLForURL:(id)url clientIdentifier:(id)identifier;
-(BOOL)_loadFromSignedDictionary:(id)signedDictionary returningError:(id*)error;
-(id)urlForKey:(id)key;
-(id)initWithURLBagContext:(id)urlbagContext;
-(BOOL)urlIsTrusted:(id)trusted;
-(id)sanitizedURLForURL:(id)url;
-(BOOL)loadFromDictionary:(id)dictionary returningError:(id*)error;
-(id)initWithRawDictionary:(id)rawDictionary;
-(BOOL)shouldSendGUIDForURL:(id)url;
-(id)copyExtraHeadersForURL:(id)url;
-(void)_writeURLResolutionCacheFile;
-(void)_writeNetworkConstraintsCacheFile;
-(id)_networkConstraintsCachePath;
-(id)_copyHeaderPatternsFromDictionary:(id)dictionary;
-(id)_copyGUIDSchemesFromDictionary:(id)dictionary;
-(id)_copyGUIDPatternsFromDictionary:(id)dictionary;
-(void)_setDictionary:(id)dictionary;
-(id)valueForKey:(id)key;
-(void)invalidate;
@end

