/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSURLCache.h>

@class NSLock, NSString, NSArray;

@interface ISURLCacheGroup : NSURLCache {
@private
	NSArray* _caches;
	NSString* _clientIdentifier;
	NSLock* _lock;
}
@property(readonly, assign) NSString* clientIdentifier;
+(id)sharedInstance;
+(void)setSharedInstance:(id)instance;
-(id)init;
-(void)dealloc;
-(void)saveMemoryCacheToDisk;
-(void)purgeMemoryCache;
-(id)initWithClientIdentifier:(id)clientIdentifier;
-(id)_ntsCacheForRequest:(id)request;
-(void)_reloadForNewCaches:(id)newCaches;
-(id)_ntsCacheForPersistentIdentifier:(id)persistentIdentifier;
-(void)setCachesFromPropertyList:(id)propertyList;
-(id)initWithMemoryCapacity:(unsigned)memoryCapacity diskCapacity:(unsigned)capacity diskPath:(id)path;
-(void)removeAllCachedResponses;
-(void)removeCachedResponseForRequest:(id)request;
-(void)setDiskCapacity:(unsigned)capacity;
-(void)setMemoryCapacity:(unsigned)capacity;
-(void)storeCachedResponse:(id)response forRequest:(id)request;
-(id)cachedResponseForRequest:(id)request;
-(unsigned)currentDiskUsage;
-(unsigned)currentMemoryUsage;
-(unsigned)diskCapacity;
-(unsigned)memoryCapacity;
@end

