/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSObject.h>

@class NSURLCache, NSString, ISURLCacheConfiguration;

@interface ISURLCache : NSObject {
@private
	NSURLCache* _cache;
	ISURLCacheConfiguration* _configuration;
}
@property(readonly, assign, nonatomic) unsigned memoryCapacity;
@property(readonly, assign, nonatomic) unsigned diskCapacity;
@property(readonly, assign, nonatomic) unsigned currentMemoryUsage;
@property(readonly, assign, nonatomic) unsigned currentDiskUsage;
@property(readonly, assign) NSString* persistentIdentifier;
+(id)cacheDirectoryPath;
+(id)persistentIdentifierFromPropertyList:(id)propertyList;
-(id)init;
-(void)dealloc;
-(void)saveMemoryCacheToDisk;
-(void)purgeMemoryCache;
-(BOOL)_urlStringMatchesURLPatterns:(id)patterns;
-(BOOL)_urlStringMatchesFileExtensions:(id)extensions;
-(BOOL)criteriaMatchesRequest:(id)request;
-(BOOL)isUsableByClientWithIdentifier:(id)identifier;
-(void)reloadWithCacheConfiguration:(id)cacheConfiguration;
-(id)initWithCacheConfiguration:(id)cacheConfiguration;
-(void)removeAllCachedResponses;
-(void)removeCachedResponseForRequest:(id)request;
-(void)storeCachedResponse:(id)response forRequest:(id)request;
-(id)cachedResponseForRequest:(id)request;
@end

