/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "ISOperation.h"

@class NSURLRequest, SSAuthenticationContext, NSURLConnection, NSMutableData, NSCountedSet, SSMutableURLRequestProperties, NSURLResponse, SSURLRequestProperties, ISDataProvider;
@protocol ISURLOperationDelegate;

@interface ISURLOperation : ISOperation {
	NSURLRequest* _activeURLRequest;
	SSAuthenticationContext* _authenticationContext;
	NSURLConnection* _connection;
	NSMutableData* _dataBuffer;
	ISDataProvider* _dataProvider;
	int _networkRetryCount;
	NSCountedSet* _redirectURLs;
	SSMutableURLRequestProperties* _requestProperties;
	NSURLResponse* _response;
	BOOL _shouldSetCookies;
}
@property(assign, getter=_shouldSetCookies, setter=_setShouldSetCookies:) BOOL _shouldSetCookies;
@property(retain) NSURLResponse* response;
@property(copy) SSURLRequestProperties* requestProperties;
@property(retain) SSAuthenticationContext* authenticationContext;
@property(retain) ISDataProvider* dataProvider;
@property(assign) id<ISURLOperationDelegate> delegate;
+(id)copyUserAgent;
-(id)init;
-(void)dealloc;
-(void)handleResponse:(id)response;
-(void)_updateProgress;
-(void)setRequest:(id)request;
-(void)_sendResponseToDelegate:(id)delegate;
-(void)_stopIfCancelled;
-(id)_copyConnectionProperties;
-(BOOL)_runRequestWithURL:(id)url;
-(void)_logRequest:(id)request;
-(void)_sendRequestToDelegate:(id)delegate;
-(BOOL)_validateContentLength:(long long)length error:(id*)error;
-(void)_sendContentLengthToDelegate:(long long)delegate;
-(void)_retry;
-(BOOL)handleRedirectFromDataProvider:(id)dataProvider;
-(id)_errorWithDomain:(id)domain code:(int)code;
-(void)_sendOutputToDelegate:(id)delegate;
-(void)_logResponseBody:(id)body;
-(void)_handleFinishedLoading;
-(id)_handleRedirectRequest:(id)request response:(id)response;
-(BOOL)shouldFollowRedirectWithRequest:(id)request returningError:(id*)error;
-(id)_sanitizedStringForString:(id)string;
-(void)_handleReceivedResponse:(id)response;
-(void)_handleReceivedData:(id)data;
-(void)_stopConnection;
-(id)_errorWithDefaultStringsForError:(id)error;
-(id)_copyAcceptLanguageString;
-(id)_accountIdentifier;
-(void)_setActiveURLRequest:(id)request;
-(id)newRequestWithURL:(id)url;
-(id)_copyQueryStringDictionaryForRedirect:(id)redirect;
-(id)_requestProperties;
-(id)_sanitizedURLForURL:(id)url;
-(id)_activeURL;
-(id)_copyAuthenticationContext;
-(void)connection:(id)connection willSendRequestForAuthenticationChallenge:(id)authenticationChallenge;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didFailWithError:(id)error;
-(id)request;
-(void)run;
-(void)_run;
-(id)connection:(id)connection willSendRequest:(id)request redirectResponse:(id)response;
@end

