/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSObject.h>
#import "iTunesStore-Structs.h"

@class NSDictionary;

@interface ISUserNotification : NSObject {
	int _allowedRetryCount;
	int _currentRetryCount;
	NSDictionary* _dictionary;
	unsigned long _optionFlags;
	NSDictionary* _userInfo;
}
@property(retain) NSDictionary* userInfo;
@property(assign) int currentRetryCount;
@property(assign) int allowedRetryCount;
@property(readonly, assign) unsigned long optionFlags;
@property(readonly, assign) NSDictionary* dictionary;
-(id)init;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary options:(unsigned long)options;
-(CFUserNotificationRef)copyUserNotification;
@end

