/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSError.h>


@interface NSError (ISAdditions)
-(BOOL)isEqual:(id)equal compareUserInfo:(BOOL)info;
-(BOOL)isFatalError;
-(id)errorBySettingFatalError:(BOOL)error;
@end

