/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <Foundation/NSFileManager.h>


@interface NSFileManager (ISAdditions)
+(BOOL)ensureDirectoryExists:(id)exists;
+(BOOL)_storeMovePath:(id)path toPath:(id)path2;
+(id)cacheDirectoryPathWithName:(id)name;
@end

