/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "NSObject.h"


@protocol SSRequestDelegate <NSObject>
@optional
-(void)requestDidFinish:(id)request;
-(void)request:(id)request didFailWithError:(id)error;
@end

