/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "NSObject.h"


@protocol SSXPCCoding <NSObject>
@optional
-(void*)copyXPCEncoding;
-(id)initWithXPCEncoding:(void*)xpcencoding;
@end

