/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class IPodLibraryItem, NSNumber;

__attribute__((visibility("hidden")))
@interface AddItemToIPodLibraryOperation : ISOperation {
	NSNumber* _insertedItemPersistentIdentifier;
	IPodLibraryItem* _libraryItem;
}
@property(readonly, assign) NSNumber* insertedItemPersistentIdentifier;
@property(readonly, assign) IPodLibraryItem* IPodLibraryItem;
-(void)_setInsertedItemPersistentIdentifier:(long long)identifier;
-(id)_libraryItem;
-(void)run;
-(void)dealloc;
-(id)initWithIPodLibraryItem:(id)ipodLibraryItem;
@end

