/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>
#import "ISOperationDelegate.h"

@class NSManagedObjectID, NSString, MicroPaymentQueueResponse, ClientIdentity;
@protocol AddMicroPaymentDelegate;

__attribute__((visibility("hidden")))
@interface AddMicroPaymentOperation : ISOperation <ISOperationDelegate> {
	NSString* _buyParameters;
	ClientIdentity* _clientIdentity;
	BOOL _needsConfirmation;
	NSManagedObjectID* _objectID;
	MicroPaymentQueueResponse* _response;
}
@property(retain) MicroPaymentQueueResponse* response;
@property(retain) NSString* buyParameters;
@property(assign) BOOL needsConfirmation;
@property(retain) ClientIdentity* clientIdentity;
@property(assign) id<AddMicroPaymentDelegate> delegate;
@property(retain) NSManagedObjectID* objectID;
-(void)_sendStateToDelegate:(int)delegate;
-(void)_runForPayment:(id)payment;
-(id)_copyConfirmOperationForPayment:(id)payment;
-(id)_copyBuyOperationForPayment:(id)payment;
-(void)run;
-(void)dealloc;
-(id)initWithObjectID:(id)objectID;
@end

