/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class SSAuthenticationContext, SSAuthenticateResponse;

__attribute__((visibility("hidden")))
@interface AuthenticateOperation : ISOperation {
	SSAuthenticationContext* _authenticationContext;
	SSAuthenticateResponse* _authenticateResponse;
}
@property(readonly, assign) SSAuthenticateResponse* authenticateResponse;
@property(readonly, assign) SSAuthenticationContext* authenticationContext;
+(BOOL)shouldOfferRetryForError:(id)error;
-(BOOL)_shouldRetryForServerResponse:(id)serverResponse;
-(BOOL)_shouldRetryForError:(id)error;
-(BOOL)_shouldRetryAfterOperationFailed:(id)failed;
-(void)_setAuthenticateResponseWithFailedAttempt:(id)failedAttempt;
-(void)_setAuthenticateResponseWithAccount:(id)account authenticationResponse:(id)response;
-(void)_setAuthenticateResponseWithAccount:(id)account type:(int)type;
-(void)_setAuthenticateResponse:(id)response;
-(BOOL)_runAuthenticationAttempts:(id*)attempts;
-(BOOL)_promptForRetryWithTitle:(id)title message:(id)message;
-(BOOL)_addAccountForAttempt:(id)attempt error:(id*)error;
-(id)_account;
-(id)uniqueKey;
-(void)run;
-(id)authenticatedAccountDSID;
-(void)dealloc;
-(id)initWithAuthenticationContext:(id)authenticationContext;
-(id)init;
@end

