/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class SSURLConnectionResponse, NSNumber, ClientIdentity;

__attribute__((visibility("hidden")))
@interface AuthorizeMachineOperation : ISOperation {
	NSNumber* _accountIdentifier;
	ClientIdentity* _clientIdentity;
	SSURLConnectionResponse* _response;
	BOOL _shouldAddKeysToKeyBag;
	id _token;
}
@property(readonly, assign) SSURLConnectionResponse* response;
@property(assign) BOOL shouldAddKeysToKeyBag;
@property(retain) ClientIdentity* clientIdentity;
@property(readonly, assign) id authorizationToken;
@property(readonly, assign) NSNumber* accountIdentifier;
-(void)_setResponse:(id)response;
-(void)_setAccountIdentifier:(id)identifier;
-(BOOL)_runAuthorization:(id*)authorization;
-(BOOL)_runAuthentication:(id*)authentication;
-(void)_run;
-(id)_newBodyDictionary;
-(BOOL)_handleResponse:(id)response error:(id*)error;
-(id)_accountIdentifier;
-(void)run;
-(void)dealloc;
-(id)initWithAuthorizationToken:(id)authorizationToken accountIdentifier:(id)identifier;
-(id)init;
@end

