/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>
#import "ISStoreURLOperationDelegate.h"

@class SignInResponse, SSAuthenticationContext, SSAuthenticationResponse;

__attribute__((visibility("hidden")))
@interface AuthenticateAttemptOperation : ISOperation <ISStoreURLOperationDelegate> {
	int _attemptNumber;
	SSAuthenticationContext* _authenticationContext;
	SSAuthenticationResponse* _authenticationResponse;
	SignInResponse* _signInResponse;
}
@property(readonly, assign) SignInResponse* signInResponse;
@property(readonly, assign) SSAuthenticationResponse* authenticationResponse;
@property(readonly, assign) SSAuthenticationContext* authenticationContext;
@property(readonly, assign) int attemptNumber;
-(void)_setSignInResponse:(id)response;
-(void)_setAuthenticationResponse:(id)response;
-(BOOL)_sendAuthenticateRequest:(id*)request;
-(id)_newAuthenticateURLOperation;
-(BOOL)_promptForCredentials:(id*)credentials;
-(id)_copyAuthenticateRequestParameters;
-(id)_account;
-(BOOL)operation:(id)operation shouldSetStoreFrontID:(id)anId;
-(id)operation:(id)operation sanitizedStringForString:(id)string;
-(void)run;
-(void)dealloc;
-(id)initWithAttemptNumber:(int)attemptNumber context:(id)context;
-(id)init;
@end

