/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class SSSoftwareUpdatesContext, SoftwareUpdateStore;

__attribute__((visibility("hidden")))
@interface CheckUpdateQueueOperation : ISOperation {
	SSSoftwareUpdatesContext* _updateQueueContext;
}
@property(readonly, assign) SoftwareUpdateStore* softwareUpdateStore;
@property(readonly, assign) SSSoftwareUpdatesContext* updateQueueContext;
-(id)_newLoadUpdateQueueOperation;
-(BOOL)_loadUpdatesFromServer:(id*)server;
-(id)uniqueKey;
-(void)run;
-(void)dealloc;
-(id)initWithUpdateQueueContext:(id)updateQueueContext;
-(id)init;
@end

