/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSNumber, NSArray, ClientIdentity;

__attribute__((visibility("hidden")))
@interface CheckoutRentalKeysOperation : ISOperation {
	NSNumber* _accountIdentifier;
	BOOL _backgroundCheckout;
	ClientIdentity* _clientIdentity;
	NSNumber* _rentalKeyIdentifier;
	NSArray* _sinfs;
}
@property(retain) ClientIdentity* clientIdentity;
@property(assign, getter=isBackgroundCheckout) BOOL backgroundCheckout;
@property(readonly, assign) NSNumber* rentalKeyIdentifier;
@property(readonly, assign) NSNumber* accountIdentifier;
@property(readonly, assign) NSArray* sinfs;
-(void)_showErrorDialogForOutput:(id)output;
-(void)_run;
-(id)_primarySINF;
-(BOOL)_performCheckout:(id*)checkout;
-(BOOL)_haveValidRentalInformation;
-(BOOL)_handleResponse:(id)response error:(id*)error;
-(id)_copyRentalIdentifier;
-(id)_copyAccountIdentifier;
-(id)_bodyData;
-(void)run;
-(void)dealloc;
-(id)initWithStoreDownloadSinfs:(id)storeDownloadSinfs;
-(id)initWithAccountIdentifier:(id)accountIdentifier rentalKeyIdentifier:(id)identifier;
-(id)initWithSinfs:(id)sinfs;
-(id)init;
@end

