/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class StoreDownloadQueueRequest;

__attribute__((visibility("hidden")))
@interface CheckDownloadQueueOperation : ISOperation {
	int _numberOfAvailableDownloads;
	StoreDownloadQueueRequest* _request;
}
@property(readonly, assign) int numberOfAvailableDownloads;
@property(readonly, assign) StoreDownloadQueueRequest* downloadQueueRequest;
-(void)_runPendingCancelDownloadOperations;
-(id)_newURLOperation;
-(id)_account;
-(void)run;
-(void)dealloc;
-(id)initWithDownloadQueueRequest:(id)downloadQueueRequest;
-(id)init;
@end

