/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSNumber, ClientIdentity;

__attribute__((visibility("hidden")))
@interface CheckinRentalOperation : ISOperation {
	NSNumber* _accountIdentifier;
	ClientIdentity* _clientIdentity;
	NSNumber* _rentalKeyIdentifier;
}
@property(retain) ClientIdentity* clientIdentity;
@property(readonly, assign) NSNumber* rentalKeyIdentifier;
@property(readonly, assign) NSNumber* accountIdentifier;
-(BOOL)_runCheckinAckOperationWithResponseData:(id)responseData error:(id*)error;
-(void)_run;
-(BOOL)_handleCheckinAckResponse:(id)response error:(id*)error;
-(BOOL)_handleResponse:(id)response error:(id*)error;
-(id)_bodyDataWithCheckinAckResponseData:(id)checkinAckResponseData;
-(id)_bodyData;
-(void)run;
-(void)dealloc;
-(id)initWithAccountIdentifier:(id)accountIdentifier rentalKeyIdentifier:(id)identifier;
-(id)init;
@end

