/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableString, NSString;

__attribute__((visibility("hidden")))
@interface CipherDataElement : NSObject {
	NSMutableString* _characterBuffer;
	NSString* _sinfID;
	NSString* _uri;
}
@property(readonly, assign, getter=isValid) BOOL valid;
@property(readonly, assign) NSString* URI;
@property(readonly, assign) NSString* sinfID;
-(void)handleElementStartWithName:(id)name namespaceURI:(id)uri attributes:(id)attributes;
-(void)handleElementEndWithName:(id)name namespaceURI:(id)uri;
-(void)handleCharacters:(id)characters;
-(void)dealloc;
@end

