/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"
#import "ISSingleton.h"

@class NSLock, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ClientObserver : NSObject <ISSingleton> {
	NSMutableArray* _clientIdentities;
	NSLock* _lock;
	NSMutableArray* _observerIdentifiers;
}
+(id)sharedInstance;
+(void)setSharedInstance:(id)instance;
-(id)_ntsClientIdentityForIdentifier:(id)identifier;
-(void)_clientStoppedListening:(id)listening;
-(void)_clientStartedListening:(id)listening;
-(void)_applicationStateChanged:(id)changed;
-(id)clientIdentityForAuditToken:(XXStruct_kUSYWB*)auditToken;
-(void)dealloc;
-(id)init;
@end

