/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ISURLOperationDelegate.h"
#import "RequestQueueOperation.h"

@class SSURLConnectionResponse, SSURLRequestProperties;

__attribute__((visibility("hidden")))
@interface ClientURLOperation : RequestQueueOperation <ISURLOperationDelegate> {
	SSURLConnectionResponse* _response;
	SSURLRequestProperties* _properties;
}
@property(readonly, assign) SSURLRequestProperties* requestProperties;
-(void)operation:(id)operation finishedWithOutput:(id)output;
-(void)run;
-(id)copyResponseDictionary;
-(id)copyRequest;
-(void)dealloc;
-(id)initWithRequest:(id)request;
@end

