/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSData, NSString, ClientIdentity;

__attribute__((visibility("hidden")))
@interface ConfirmMicroPaymentOperation : ISOperation {
	NSString* _buyParameters;
	ClientIdentity* _clientIdentity;
	NSString* _productIdentifier;
	int _quantity;
	NSData* _requestData;
}
@property(retain) NSString* buyParameters;
@property(retain) NSData* requestData;
@property(assign) int quantity;
@property(retain) NSString* productIdentifier;
@property(retain) ClientIdentity* clientIdentity;
-(BOOL)_promptUserWithServerDialog:(id)serverDialog returningError:(id*)error;
-(void)_fetchAndDisplayConfirmation;
-(id)_errorForFailureType:(id)failureType;
-(id)_copyResponseReturningError:(id*)error;
-(id)_copyResponseForApplication:(id)application returningError:(id*)error;
-(id)_copyQueryStringDictionaryForApplication:(id)application;
-(BOOL)_canPromptWithServerDialog:(id)serverDialog;
-(void)run;
-(void)dealloc;
@end

