/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableSet, SSXPCConnection, NSArray;

__attribute__((visibility("hidden")))
@interface DistributedNotificationObserver : NSObject {
	SSXPCConnection* _connection;
	NSMutableSet* _notificationNames;
}
@property(readonly, assign, nonatomic) NSArray* observedNotificationNames;
-(void)removeObservedNotificationName:(id)name;
-(void)postNotificationName:(id)name message:(void*)message;
-(void)addObservedNotificationNames:(id)names;
-(void)addObservedNotificationName:(id)name;
-(void)dealloc;
-(id)initWithServiceName:(id)serviceName;
@end

