/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface DistributedNotificationCenter : NSObject {
	dispatch_queue_s* _dispatchQueue;
	NSMutableDictionary* _observers;
}
+(id)defaultCenter;
-(void)_saveRegisteredPortNames;
-(void)unregisterObserverWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)registerObserverWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)postNotificationName:(CFStringRef)name;
-(void)dealloc;
-(id)init;
@end

