/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface DownloadDatabaseSchema {
}
+(BOOL)_migrateToCurrentUserVersionUsingDatabase:(id)currentUserVersionUsingDatabase;
+(id)databasePath;
+(void)createSchemaInDatabase:(id)database;
+(void)createFunctionsInDatabase:(id)database;
@end

