/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>
#import "DownloadSessionDelegate.h"
#import "itunesstored-Structs.h"

@class DownloadSessionProperties;

__attribute__((visibility("hidden")))
@interface DownloadSessionOperation : ISOperation <DownloadSessionDelegate> {
	dispatch_semaphore_s* _semaphore;
	DownloadSessionProperties* _sessionProperties;
	BOOL _shouldLaunchDownloadHandler;
	int _state;
}
@property(readonly, assign) int downloadSessionState;
@property(assign) BOOL shouldLaunchDownloadHandler;
@property(readonly, assign) DownloadSessionProperties* sessionProperties;
-(void)_setState:(int)state;
-(void)_sendBeginMessageForSession:(id)session;
-(void)downloadSession:(id)session didUpdateProgress:(double)progress;
-(void)downloadSession:(id)session didFinishAuthenticationWithType:(int)type credential:(id)credential;
-(void)downloadSession:(id)session didFailWithError:(id)error;
-(void)downloadSessionDidRelease:(id)downloadSession;
-(void)downloadSessionDidFinish:(id)downloadSession;
-(void)downloadSessionDidDisconnect:(id)downloadSession;
-(void)run;
-(void)cancel;
-(void)dealloc;
-(id)initWithSessionProperties:(id)sessionProperties;
@end

