/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import "XPCClient.h"

@class NSMutableSet, NSSet;

__attribute__((visibility("hidden")))
@interface DownloadHandlerClient : XPCClient {
	NSMutableSet* _disavowedSessionProperties;
	NSSet* _downloadPhasesToIgnore;
	BOOL _sessionsNeedPowerAssertion;
	BOOL _sessionsShouldBlockOtherDownloads;
}
@property(assign) BOOL sessionsShouldBlockOtherDownloads;
@property(assign) BOOL sessionsNeedPowerAssertion;
@property(copy) NSSet* downloadPhasesToIgnore;
@property(readonly, assign) NSSet* disavowedSessionProperties;
-(id)description;
-(id)resetDisavowedSessionProperties;
-(void)addDisavowedSessionProperties:(id)properties;
-(void)dealloc;
-(id)initWithInputConnection:(xpc_connection_s*)inputConnection;
@end

