/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol DownloadSessionDelegate <NSObject>
@optional
-(void)downloadSession:(id)session didUpdateProgress:(double)progress;
-(void)downloadSession:(id)session didChangeStatusDescription:(id)description;
-(void)downloadSession:(id)session didFailWithError:(id)error;
-(void)downloadSession:(id)session didFinishAuthenticationWithType:(int)type credential:(id)credential;
-(void)downloadSession:(id)session didDisavowWithError:(id)error;
-(void)downloadSessionPropertiesDidChange:(id)downloadSessionProperties;
-(void)downloadSessionDidRelease:(id)downloadSession;
-(void)downloadSessionDidFinish:(id)downloadSession;
-(void)downloadSessionDidDisconnect:(id)downloadSession;
@end

