/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"
#import "NSCopying.h"

@class NSOrderedSet, NSString, NSMutableOrderedSet;

__attribute__((visibility("hidden")))
@interface DownloadError : NSObject <NSCopying> {
	NSMutableOrderedSet* _downloadIdentifiers;
	NSString* _downloadKind;
	NSString* _downloadTitle;
	id _notification;
	id __notification;
}
@property(retain, nonatomic, getter=_notification, setter=_setNotification:) id _notification;
@property(readonly, assign, nonatomic, getter=isValidError) BOOL validError;
@property(copy, nonatomic) NSString* downloadTitle;
@property(copy, nonatomic) NSString* downloadKind;
@property(readonly, assign, nonatomic) NSOrderedSet* downloadIdentifiers;
-(id)copyWithZone:(NSZone*)zone;
-(BOOL)representsDownloadWithIdentifier:(long long)identifier;
-(void)removeDownloadIdentifier:(long long)identifier;
-(void)performActionForResponseFlags:(unsigned long)responseFlags;
-(id)copyUserNotification;
-(BOOL)canCoalesceWithError:(id)error;
-(void)addDownloadIdentifiers:(id)identifiers;
-(void)addDownloadIdentifier:(long long)identifier;
-(void)dealloc;
@end

