/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class SinfsArray, NSArray;

__attribute__((visibility("hidden")))
@interface DownloadDRM : NSObject {
	NSArray* _sinfs;
}
@property(readonly, assign) SinfsArray* sinfsArray;
@property(readonly, assign) SinfsArray* pinfsArray;
@property(readonly, assign) NSArray* sinfs;
-(id)_sinfsArrayWithDataKey:(id)dataKey;
-(id)sinfForIdentifier:(int)identifier;
-(id)firstDataForSinfDataKey:(id)sinfDataKey;
-(void)dealloc;
-(id)initWithSinfArray:(id)sinfArray;
-(id)init;
@end

