/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class DownloadManagerClient;

__attribute__((visibility("hidden")))
@interface DownloadArtworkCacheRequest : NSObject {
	DownloadManagerClient* _requestClient;
	void* _requestMessage;
}
@property(assign, nonatomic) void* requestMessage;
@property(retain, nonatomic) DownloadManagerClient* requestClient;
-(void)finishWithData:(id)data error:(id)error;
-(void)dealloc;
@end

