/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import "SQLiteEntity.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface Download : SQLiteEntity {
}
@property(readonly, assign, nonatomic) NSString* ITunesSafeGUID;
@property(readonly, assign, nonatomic) unsigned long long itemIdentifier;
@property(readonly, assign, nonatomic) NSString* downloadKind;
+(void)initialize;
+(id)joinClauseForProperty:(id)property;
+(id)foreignKeyColumnForTable:(id)table;
+(id)foreignDatabaseTablesToDelete;
+(id)foreignDatabaseTableForProperty:(id)property;
+(id)foreignDatabaseColumnForProperty:(id)property;
+(id)disambiguatedSQLForProperty:(id)property;
+(id)databaseTable;
+(id)databasePropertyToSetClientProperty:(id)setClientProperty;
+(id)databasePropertyToGetClientProperty:(id)getClientProperty;
+(id)newNetworkConstraintsWithDownloadKind:(id)downloadKind URLBagType:(int)type sizeLimits:(id*)limits;
+(id)newDownloadKeyCookieWithValue:(id)value URL:(id)url;
+(id)copyValueDictionaryWithMetadata:(id)metadata;
-(void)_resetAssetProperty:(id)property;
-(id)_rentalInformation;
-(id)_databaseAssetForImportAsset:(id)importAsset;
-(int)_addPersistentDownloadsWithClientID:(id)clientID kind:(id)kind;
-(id)valueForExternalProperty:(id)externalProperty;
-(void)setExternalValuesWithDictionary:(id)dictionary;
-(BOOL)deleteFromDatabase;
-(BOOL)setAssetsUsingImportDownload:(id)download changeInfo:(DownloadChangeInfo*)info;
-(void)resetAssetURLs;
-(void)resetAssetLocalPaths;
-(id)networkConstraintsWithBagType:(int)bagType;
-(BOOL)isNetworkConstrainedForAssetID:(long long)assetID error:(id*)error;
-(BOOL)finishWithFinalPhase:(id)finalPhase changeInfo:(DownloadChangeInfo*)info;
-(void)deleteCookiesFromSharedCookieStorage;
-(id)copyStoreDownloadMetadata;
-(id)copyDownloadKeyCookie;
-(id)copyDownloadingIPodLibraryItem;
-(id)copyAdditionalMetadataForStoreDownload:(id)storeDownload;
-(id)anyAssetForAssetType:(id)assetType;
@end

