/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"

@class DownloadHandlerClient, NSString, DownloadSessionProperties;
@protocol DownloadSessionDelegate;

__attribute__((visibility("hidden")))
@interface DownloadSession : NSObject {
	BOOL _blocksOtherDownloads;
	BOOL _canBePaused;
	DownloadHandlerClient* _client;
	id<DownloadSessionDelegate> _delegate;
	dispatch_queue_s* _dispatchQueue;
	BOOL _needsPowerAssertion;
	DownloadSessionProperties* _properties;
	long long _sessionID;
	NSString* _statusDescription;
}
@property(copy) NSString* statusDescription;
@property(readonly, assign) DownloadSessionProperties* sessionProperties;
@property(readonly, assign) long long sessionIdentifier;
@property(readonly, assign) DownloadHandlerClient* client;
@property(assign) BOOL needsPowerAssertion;
@property(assign) BOOL canBePaused;
@property(assign) BOOL blocksOtherDownloads;
@property(assign) id<DownloadSessionDelegate> delegate;
-(id)description;
-(void)setPropertiesWithValues:(void*)values;
-(void)setPercentComplete:(double)complete;
-(void)sendSessionMessage:(long long)message withReply:(id)reply;
-(void)finishWithType:(int)type message:(void*)message;
-(void)disconnect;
-(void)dealloc;
-(id)initWithClient:(id)client properties:(id)properties queue:(dispatch_queue_s*)queue;
@end

