/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface DownloadAssetOperation : ISOperation {
	long long _assetID;
	long long _downloadID;
}
@property(readonly, assign) NSString* localAssetPath;
@property(readonly, assign) long long downloadIdentifier;
@property(readonly, assign) long long assetIdentifier;
-(void)updateAssetWithContentLength:(id)contentLength response:(id)response;
-(id)newURLOperationWithRequestProperties:(id)requestProperties;
-(id)newStoreURLOperationWithRequestProperties:(id)requestProperties;
-(BOOL)handleAuthenticationChallenge:(id)challenge;
-(id)initWithAssetIdentifier:(long long)assetIdentifier downloadIdentifier:(long long)identifier;
@end

