/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"
#import "NSCopying.h"

@class NSString, NSURLAuthenticationChallenge;

__attribute__((visibility("hidden")))
@interface DownloadSessionProperties : NSObject <NSCopying> {
	long long _assetID;
	NSURLAuthenticationChallenge* _authenticationChallenge;
	NSString* _clientIdentifier;
	long long _downloadID;
	NSString* _downloadPhase;
	long long _handlerIdentifier;
}
@property(assign, nonatomic) long long handlerIdentifier;
@property(copy, nonatomic) NSString* clientIdentifier;
@property(copy, nonatomic) NSString* downloadPhase;
@property(assign, nonatomic) long long downloadIdentifier;
@property(retain, nonatomic) NSURLAuthenticationChallenge* authenticationChallenge;
@property(assign, nonatomic) long long assetIdentifier;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
@end

