/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface DownloadSinf : NSObject {
	NSDictionary* _info;
}
@property(readonly, assign) int identifier;
-(id)dataForSinfDataKey:(id)sinfDataKey;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary;
-(id)init;
@end

