/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DownloadError.h"
#import "itunesstored-Structs.h"
#import "NSCopying.h"

@class NSError;

__attribute__((visibility("hidden")))
@interface DownloadGenericError : DownloadError <NSCopying> {
	NSError* _error;
}
@property(readonly, assign, nonatomic) NSError* error;
-(id)copyWithZone:(NSZone*)zone;
-(id)_notificationTitle;
-(id)_notificationBody;
-(BOOL)_isInstallError:(id)error;
-(void)performActionForResponseFlags:(unsigned long)responseFlags;
-(id)copyUserNotification;
-(BOOL)canCoalesceWithError:(id)error;
-(void)dealloc;
-(id)initWithError:(id)error;
@end

