/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"

@class NSMutableArray, NSMutableOrderedSet;

__attribute__((visibility("hidden")))
@interface DownloadErrorController : NSObject {
	dispatch_queue_s* _dispatchQueue;
	NSMutableArray* _errors;
	NSMutableOrderedSet* _scheduledErrors;
	dispatch_source_s* _scheduledErrorTimer;
}
+(id)sharedErrorController;
-(void)_scheduleErrorDisplay:(id)display;
-(void)_displayScheduledErrors;
-(void)_cancelErrorsPassingTest:(id)test;
-(void)_networkTypeChangedNotification:(id)notification;
-(void)showDownloadError:(id)error;
-(void)cancelDialogsWithDownloadIdentifier:(long long)downloadIdentifier;
-(void)dealloc;
-(id)init;
@end

