/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"

@class NSMutableDictionary, ISOperationQueue;

__attribute__((visibility("hidden")))
@interface DownloadArtworkCache : NSObject {
	dispatch_queue_s* _dispatchQueue;
	ISOperationQueue* _operationQueue;
	NSMutableDictionary* _requests;
}
+(id)sharedCache;
-(void)_finishArtworkOperation:(id)operation;
-(void)_enqueueOperationForDownload:(id)download;
-(id)_copyClientForConnection:(xpc_connection_s*)connection;
-(void)_clientDisconnectNotification:(id)notification;
-(void)loadDownloadThumbnailWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)dealloc;
-(id)init;
@end

