/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import "DownloadError.h"
#import "NSCopying.h"


__attribute__((visibility("hidden")))
@interface DownloadDiskSpaceError : DownloadError <NSCopying> {
}
-(id)copyWithZone:(NSZone*)zone;
-(void)performActionForResponseFlags:(unsigned long)responseFlags;
-(id)copyUserNotification;
-(BOOL)canCoalesceWithError:(id)error;
@end

