/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XPCClient.h"

@class NSSet, NSString, NSArray;

__attribute__((visibility("hidden")))
@interface DownloadManagerClient : XPCClient {
	NSSet* _downloadKinds;
	NSString* _persistenceIdentifier;
	NSArray* _prefetchedDownloadExternalProperties;
	NSArray* _prefetchedDownloadProperties;
	BOOL _shouldFilterExternalDownloads;
}
@property(assign) BOOL shouldFilterExternalDownloads;
@property(copy) NSArray* prefetchedDownloadProperties;
@property(copy) NSArray* prefetchedDownloadExternalProperties;
@property(copy) NSString* persistenceIdentifier;
@property(copy) NSSet* downloadKinds;
-(void)_sendCoalescableMessage:(unsigned long long)message withDownloadIDs:(id)downloadIDs;
-(id)_copyFilteredKindsForKinds:(id)kinds;
-(id)_copyPrivateDownloadKinds;
-(id)_copyDownloadKindsFromEntitlement;
-(id)_copyAllowedThirdPartyKinds;
-(BOOL)supportsDownloadKind:(id)kind;
-(void)setClientOptions:(void*)options;
-(void)sendDownloadsUpdatedWithIdentifiers:(id)identifiers;
-(void)sendDownloadStatesChangedWithIdentifiers:(id)identifiers;
-(void)sendDownloadStateChangedWithID:(long long)anId externalValues:(id)values propertyValues:(id)values3;
-(void)sendDownloadsRemovedWithIdentifiers:(id)identifiers;
-(void)reloadPersistenceStateInDatabase:(id)database;
-(id)persistentDownloadManagerInDatabase:(id)database;
-(void)dealloc;
@end

