/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "EntityImport.h"


__attribute__((visibility("hidden")))
@interface DownloadAssetImport : EntityImport {
}
+(Class)entityClass;
-(id)initWithStoreDownload:(id)storeDownload assetType:(id)type;
-(id)initWithExternalManifestDictionary:(id)externalManifestDictionary;
-(id)initWithClientXPCObject:(void*)clientXPCObject;
@end

