/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"
#import "MCProfileConnectionObserver.h"

@class DownloadPipeline, NSMutableArray, NSCountedSet;

__attribute__((visibility("hidden")))
@interface DownloadManager : NSObject <MCProfileConnectionObserver> {
	NSMutableArray* _clients;
	dispatch_queue_s* _dispatchQueue;
	DownloadPipeline* _downloadPipeline;
	NSCountedSet* _networkUsage;
	BOOL _scheduledFailedRestoreRetry;
}
+(id)sharedManager;
+(void)retryAllRestoreDownloads;
+(id)downloadsDatabase;
+(BOOL)client:(id)client canAccessDownload:(id)download;
-(void)_wakeupApplicationWithDisplayID:(id)displayID libraryID:(id)anId;
-(void)_runFinishDownloadsOperation;
-(id)_retryRestoreDownloadsWithPredicate:(id)predicate inDatabase:(id)database changeInfo:(DownloadChangeInfo*)info;
-(void)_retryDownloadWithID:(long long)anId database:(id)database changeInfo:(DownloadChangeInfo*)info shouldTriggerRestore:(BOOL*)restore;
-(void)_resetRestrictionSettings;
-(void)_prioritizeDownloadsWithKind:(id)kind clientID:(id)anId;
-(double)_orderKeyAdjacentToOrderKey:(double)orderKey comparisonType:(int)type;
-(id)_importDownloads:(id)downloads initialOrderKey:(double)key orderKeyIncrement:(double)increment changeInfo:(DownloadChangeInfo*)info;
-(void)_handleSessionControlSelector:(SEL)selector withMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)_handleMessage:(void*)message connection:(xpc_connection_s*)connection usingReplyBlock:(id)block;
-(void)_handleMessage:(void*)message connection:(xpc_connection_s*)connection usingBlock:(id)block;
-(id)_downloadsQueryForClient:(id)client message:(void*)message database:(id)database;
-(id)_downloadsQueryForGlobalActiveDownloadsWithDatabase:(id)database;
-(BOOL)_deletePersistentDownloadManager:(id)manager;
-(id)_clientForConnection:(xpc_connection_s*)connection;
-(BOOL)_client:(id)client canAccessAsset:(id)asset;
-(void)profileConnectionDidReceiveRestrictionChangedNotification:(id)profileConnection userInfo:(id)info;
-(void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)profileConnection userInfo:(id)info;
-(void)_retrySoftFailedRestoreDownloadsNotification:(id)notification;
-(void)_retryFailedRestoreDownloadsNotification:(id)notification;
-(void)_retryCanceledRestoreDownloadsNotification:(id)notification;
-(void)_networkTypeChanged:(id)changed;
-(void)_clientDisconnectNotification:(id)notification;
-(void)_clientApplicationStateChangedNotification:(id)notification;
-(void)_carrierSettingsChangedNotification:(id)notification;
-(void)setSessionStatusDescriptionWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)setSessionPropertiesWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)setSessionProgressWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)setHandlerPropertiesWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)setClientDownloadHandlerWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)resetDisavowedSessionsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)getSessionPropertiesWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)finishSessionWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)connectDownloadHandlerWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)setDownloadsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)setDownloadPropertiesWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)setDownloadHandlerWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)setAssetPropertiesWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)resumeDownloadsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)removePersistenceIDWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)reloadDownloadManagerWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)registerClientDownloadManager:(void*)manager connection:(xpc_connection_s*)connection;
-(void)reevaluateBackgroundDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)prioritizeDownloadWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)pauseDownloadsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)moveDownloadWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)insertDownloadsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)getEntityExistsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)getDownloadsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)getDownloadPropertiesWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)getDownloadKindsUsingNetworkMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)getDownloadAssetsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)getDownloadAssetPropertiesWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)getActiveDownloadsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)finishDownloadsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)cancelDownloadsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)cancelAllDownloadsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(BOOL)updateDownload:(id)download withImportDownload:(id)importDownload changeInfo:(DownloadChangeInfo*)info;
-(void)sendStateChangeNotificationForDownloadID:(long long)downloadID kind:(id)kind propertyValues:(id)values;
-(void)sendStateChangeNotificationForDownloadID:(long long)downloadID kind:(id)kind;
-(void)scheduleRetryFailedRestoreDownloads;
-(BOOL)retryDownloadsWithIdentifiers:(id)identifiers;
-(void)rebuildDownloadPipeline;
-(void)modifyDownloadsWithTransactionBlock:(id)transactionBlock;
-(id)insertImportDownloads:(id)downloads beforeDownloadWithPersistentID:(long long)persistentID changeInfo:(DownloadChangeInfo*)info;
-(id)insertImportDownloads:(id)downloads afterDownloadWithPersistentID:(long long)persistentID changeInfo:(DownloadChangeInfo*)info;
-(BOOL)finishDownload:(id)download withFinalPhase:(id)finalPhase changeInfo:(DownloadChangeInfo*)info;
-(void)fillDownloadPipeline;
-(void)endUsingNetworkForDownloadKind:(id)downloadKind;
-(id)downloadForPersistentID:(long long)persistentID;
-(BOOL)cancelDownloadsWithIdentifiers:(id)identifiers changeInfo:(DownloadChangeInfo*)info;
-(void)beginUsingNetworkForDownloadKind:(id)downloadKind;
-(id)addImportDownloads:(id)downloads changeInfo:(DownloadChangeInfo*)info;
-(void)dealloc;
-(id)init;
@end

