/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"

@class NSMutableDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface DownloadSessionController : NSObject {
	NSMutableDictionary* _allHandlers;
	NSMutableDictionary* _clientHandlers;
	dispatch_queue_s* _dispatchQueue;
	NSMutableArray* _sessions;
}
+(id)sharedController;
-(void)_setPropertiesForClient:(id)client usingConnectionMessage:(void*)message;
-(id)_sessionForSessionIdentifier:(long long)sessionIdentifier;
-(void)_handleMessage:(void*)message connection:(xpc_connection_s*)connection usingReplyBlock:(id)block;
-(void)_handleMessage:(void*)message connection:(xpc_connection_s*)connection usingBlock:(id)block;
-(void)_disconnectSessionsPassingTest:(id)test;
-(id)_clientForSessionProperties:(id)sessionProperties;
-(id)_clientForClientID:(id)clientID handlerID:(id)anId;
-(void)_clientDisconnectNotification:(id)notification;
-(void)setSessionStatusDescriptionWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)setSessionPropertiesWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)setSessionProgressWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)setHandlerPropertiesWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)setClientDownloadHandlerWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)resetDisavowedSessionsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)getSessionPropertiesWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)finishSessionWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)connectDownloadHandlerWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(id)openSessionWithProperties:(id)properties;
-(id)handlerForSessionProperties:(id)sessionProperties;
-(id)handlerForHandlerIdentifier:(long long)handlerIdentifier;
-(void)closeSession:(id)session;
-(void)dealloc;
-(id)init;
@end

