/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface EBookManifest : NSObject {
	dispatch_queue_s* _dispatchQueue;
	NSMutableDictionary* _manifest;
	NSString* _manifestPath;
}
@property(readonly, assign) NSString* manifestPath;
+(id)syncedBookManifest;
+(id)purchasedBookManifest;
-(id)_manifest;
-(void)_invalidateAfterExternalChange;
-(id)_entries;
-(void)synchronizeData;
-(id)manifestEntriesWithProperty:(id)property equalToValue:(id)value limitCount:(int)count;
-(void)addManifestEntries:(id)entries;
-(void)addManifestEntry:(id)entry;
-(void)dealloc;
-(id)initWithManifestPath:(id)manifestPath;
-(id)init;
@end

