/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "NSXMLParserDelegate.h"

@class NSMutableArray, NSArray;

__attribute__((visibility("hidden")))
@interface EncryptedFileManifest : NSObject <NSXMLParserDelegate> {
	NSMutableArray* _elementStack;
	NSMutableArray* _fileReferences;
}
@property(readonly, assign) NSArray* fileReferences;
-(void)parser:(id)parser foundCharacters:(id)characters;
-(void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;
-(void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;
-(void)dealloc;
-(id)initWithData:(id)data error:(id*)error;
-(id)init;
@end

