/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface EncryptedFileReference : NSObject {
	NSString* _sinfID;
	NSString* _uri;
}
@property(readonly, assign) NSString* URI;
@property(readonly, assign) NSString* sinfID;
-(void)dealloc;
-(id)initWithCipherDataElement:(id)cipherDataElement;
@end

