/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface EntityImport : NSObject {
	NSMutableDictionary* _databaseProperties;
	NSMutableDictionary* _externalProperties;
	long long _persistentIdentifier;
}
@property(readonly, assign) long long persistentIdentifier;
@property(readonly, assign, nonatomic) NSMutableDictionary* externalProperties;
@property(readonly, assign, nonatomic) NSMutableDictionary* databaseProperties;
+(Class)entityClass;
-(id)existingEntityInDatabase:(id)database;
-(void)dealloc;
-(id)initWithDatabaseProperties:(id)databaseProperties;
-(id)initWithClientXPCObject:(void*)clientXPCObject;
@end

