/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import "EventMonitorEvent.h"
#import "NSCopying.h"


__attribute__((visibility("hidden")))
@interface EventMonitorBlockEvent : EventMonitorEvent <NSCopying> {
	id _eventBlock;
	id _testBlock;
}
@property(copy, nonatomic) id testBlock;
@property(copy, nonatomic) id eventBlock;
-(id)copyWithZone:(NSZone*)zone;
-(void)performAction;
-(BOOL)hasOccurred;
-(void)dealloc;
@end

