/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import "NSCopying.h"
#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface EventMonitorEvent : NSObject <NSCopying> {
	double _lastOccurrenceCheckTime;
	int _pollInterval;
	BOOL _shouldKeepDaemonAlive;
}
@property(assign, nonatomic, getter=_lastOccurrenceCheckTime, setter=_setLastOccurrenceCheckTime:) double _lastOccurrenceCheckTime;
@property(assign, nonatomic) BOOL shouldKeepDaemonAlive;
@property(assign, nonatomic) int pollInterval;
@property(readonly, assign, nonatomic) BOOL hasOccurred;
-(id)copyWithZone:(NSZone*)zone;
-(void)performAction;
-(id)init;
@end

