/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import <Foundation/NSObject.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface EventDispatcher : NSObject {
	dispatch_queue_s* _dispatchQueue;
	NSMutableArray* _eventMonitors;
}
+(id)eventDispatcher;
-(void)_clientDisconnectNotification:(id)notification;
-(void)connectEventMonitorWithMessage:(void*)message connection:(xpc_connection_s*)connection;
-(void)postEventWithName:(id)name userInfo:(id)info;
-(void)dealloc;
-(id)init;
@end

