/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface ExtractFileOperation : ISOperation {
	long long _activeFileBytesCopied;
	NSString* _activeFilePath;
	NSString* _destinationFilePath;
	double _lastSnapshotTime;
	BOOL _shouldMakeDestinationReadWritable;
	NSString* _sourceFilePath;
	int _sourceFileType;
}
@property(assign) int sourceFileType;
@property(retain) NSString* sourceFilePath;
@property(assign) BOOL shouldMakeDestinationReadWritable;
@property(retain) NSString* destinationFilePath;
-(void)_updateProgressWithByteCount:(long long)byteCount;
-(BOOL)_performBOMCopy:(id*)copy;
-(id)_newBOMCopierOptions;
-(void)_initializeProgress;
-(BOOL)_fixFilePermissionsForDirectory:(id)directory error:(id*)error;
-(void)_copierUpdatedFileWithPath:(const char*)path size:(long long)size;
-(void)_copierStartedFileWithPath:(const char*)path size:(long long)size;
-(void)_copierFinishedFileWithPath:(const char*)path size:(long long)size;
-(void)run;
-(void)dealloc;
@end

