/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSData, NSString;

__attribute__((visibility("hidden")))
@interface FairPlayDecryptFileOperation : ISOperation {
	NSData* _dpInfo;
	double _lastSnapshotTime;
	NSString* _path;
}
-(void)_updateProgressWithByteCount:(long long)byteCount;
-(void)_initializeProgressWithFileHandle:(id)fileHandle;
-(BOOL)_decryptWithSession:(void*)session error:(id*)error;
-(void)run;
-(void)dealloc;
-(id)initWithPath:(id)path dpInfo:(id)info;
-(id)init;
@end

