/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DownloadAssetOperation.h"
#import "itunesstored-Structs.h"
#import "ISURLOperationDelegate.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface FetchAssetOperation : DownloadAssetOperation <ISURLOperationDelegate> {
	NSNumber* _bytesTotal;
	BOOL _isRestoreDownload;
	dispatch_source_s* _diskSpaceSource;
	dispatch_source_s* _diskSpaceTimer;
}
-(void)_startDiskSpaceSource;
-(void)_setBytesTotal:(long long)total;
-(void)_logDownloadEvent:(id)event withURLString:(id)urlstring size:(id)size kind:(id)kind client:(id)client;
-(void)_handleDiskSpaceEvent;
-(BOOL)_downloadRegularAsset:(id)asset error:(id*)error;
-(BOOL)_downloadPlayableAsset:(id)asset error:(id*)error;
-(BOOL)_downloadAsset:(id)asset withKind:(id)kind error:(id*)error;
-(BOOL)_checkAvailableSpaceForSize:(long long)size error:(id*)error;
-(void)_cancelDiskSpaceTimer;
-(void)_cancelDiskSpaceSource;
-(void)operationFinished:(id)finished;
-(void)operation:(id)operation updatedProgress:(id)progress;
-(BOOL)operation:(id)operation willSendRequestForAuthenticationChallenge:(id)authenticationChallenge;
-(void)operation:(id)operation didDiscoverContentLength:(id)length;
-(void)run;
-(void)cancel;
-(void)dealloc;
@end

