/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class SQLitePredicate;

__attribute__((visibility("hidden")))
@interface FinishDownloadsOperation : ISOperation {
	SQLitePredicate* _predicate;
}
@property(readonly, assign) SQLitePredicate* finishedDownloadPredicate;
-(void)run;
-(void)dealloc;
-(id)initWithFinishedDownloadPredicate:(id)finishedDownloadPredicate;
@end

