/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class SSAuthenticationContext, NSArray;

__attribute__((visibility("hidden")))
@interface GetAutomaticDownloadKindsOperation : ISOperation {
	SSAuthenticationContext* _authContext;
	NSArray* _enabledDownloadKinds;
}
@property(readonly, assign) NSArray* enabledDownloadKinds;
@property(copy) SSAuthenticationContext* authenticationContext;
-(void)run;
-(void)dealloc;
@end

