/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class SSPlayInfoRequestContext, SSPlayInfoResponse, ClientIdentity;

__attribute__((visibility("hidden")))
@interface GetPlayInfoOperation : ISOperation {
	ClientIdentity* _clientIdentity;
	SSPlayInfoRequestContext* _context;
	SSPlayInfoResponse* _response;
}
@property(readonly, assign) SSPlayInfoResponse* playInfoResponse;
@property(retain) ClientIdentity* clientIdentity;
@property(readonly, assign) SSPlayInfoRequestContext* playInfoContext;
-(void)_setResponseForOutput:(id)output;
-(void)_setPlayInfoResponse:(id)response;
-(void)_failWithError:(id)error;
-(id)_copyRequestBody:(id*)body;
-(void)run;
-(void)dealloc;
-(id)initWithPlayInfoRequestContext:(id)playInfoRequestContext;
@end

