/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import <iTunesStore/ISOperation.h>

@class SoftwareProperties;

__attribute__((visibility("hidden")))
@interface InstallSoftwareOperation : ISOperation {
	SoftwareProperties* _softwareProperties;
}
@property(readonly, assign) SoftwareProperties* softwareProperties;
-(void)_setProgress:(int)progress;
-(void)_setInstallationErrorWithCode:(CFStringRef)code name:(CFStringRef)name;
-(CFDictionaryRef)_newInstallationOptions;
-(BOOL)_installPackage;
-(void)run;
-(void)dealloc;
-(id)initWithSoftwareProperties:(id)softwareProperties;
@end

