/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "InstallDownloadOperation.h"


__attribute__((visibility("hidden")))
@interface InstallToneDownloadOperation : InstallDownloadOperation {
}
-(void)_updateRingtonesPlistWithRingtoneGUID:(id)ringtoneGUID downloadID:(long long)anId installProperties:(id)properties;
-(id)_newRingtoneDictionaryWithRingtoneGUID:(id)ringtoneGUID downloadID:(long long)anId installProperties:(id)properties;
-(void)run;
@end

