/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ISOperationDelegate.h"
#import <iTunesStore/ISOperation.h>


__attribute__((visibility("hidden")))
@interface InstallDownloadOperation : ISOperation <ISOperationDelegate> {
	long long _downloadID;
}
@property(readonly, assign) long long downloadIdentifier;
-(void)operationFinished:(id)finished;
-(void)operation:(id)operation updatedProgress:(id)progress;
-(void)run;
-(void)writeStoreMetadataWithPath:(id)path download:(id)download installProperties:(id)properties additionalInfo:(id)info;
-(BOOL)saveInstallURLsForInstallProperties:(id)installProperties download:(id)download error:(id*)error;
-(BOOL)rollbackAllFilesForInstallProperties:(id)installProperties error:(id*)error;
-(BOOL)installAllFilesForInstallProperties:(id)installProperties error:(id*)error;
-(id)initWithDownloadIdentifier:(long long)downloadIdentifier;
@end

