/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "InstallDownloadOperation.h"


__attribute__((visibility("hidden")))
@interface InstallDocumentDownloadOperation : InstallDownloadOperation {
}
-(BOOL)_installRegularDocumentWithDownload:(id)download installProperties:(id)properties error:(id*)error;
-(BOOL)_installIBooksDocumentWithDownload:(id)download installProperties:(id)properties error:(id*)error;
-(id)_documentsPathForInstallProperties:(id)installProperties;
-(void)run;
@end

