/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary, PurchaseManifestItem, NSArray, StoreDownload;

__attribute__((visibility("hidden")))
@interface InstallDownloadProperties : NSObject {
	NSMutableDictionary* _installedFileNames;
	NSMutableDictionary* _installedURLs;
	NSMutableDictionary* _propertyValues;
	PurchaseManifestItem* _purchaseManifestItem;
	NSMutableDictionary* _scratchFilePaths;
	StoreDownload* _storeDownload;
}
@property(readonly, assign, nonatomic) StoreDownload* storeDownload;
@property(readonly, assign, nonatomic) PurchaseManifestItem* purchaseManifestItem;
@property(readonly, assign, nonatomic) NSArray* allInstalledFileNames;
@property(readonly, assign, nonatomic) NSArray* allScratchFilePaths;
-(id)valueForDownloadProperty:(id)downloadProperty;
-(void)setValue:(id)value forDownloadProperty:(id)downloadProperty;
-(void)setInstalledURL:(id)url forAssetType:(id)assetType;
-(id)scratchFilePathForAssetType:(id)assetType;
-(id)installedURLForAssetType:(id)assetType;
-(id)installedFileNameForAssetType:(id)assetType;
-(void)dealloc;
-(id)initWithDownload:(id)download properties:(id*)properties count:(unsigned)count;
@end

