/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "InstallDownloadOperation.h"


__attribute__((visibility("hidden")))
@interface InstallEBookDownloadOperation : InstallDownloadOperation {
}
-(BOOL)_writeEPRDataWithPath:(id)path installProperties:(id)properties error:(id*)error;
-(id)_syncedBooksPath;
-(id)_storeFrontIdentifierForInstallProperties:(id)installProperties;
-(id)_newManifestEntryWithBookFileName:(id)bookFileName installProperties:(id)properties;
-(id)_installFilesForDownload:(id)download installProperties:(id)properties manifest:(id)manifest;
-(void)_addToPurchaseManifest:(id)purchaseManifest withBookPath:(id)bookPath installProperties:(id)properties existingEntry:(id)entry;
-(void)run;
@end

