/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"

@class ISOperationQueue, NSMutableArray;

__attribute__((visibility("hidden")))
@interface IPodLibrary : NSObject {
	dispatch_queue_s* _dispatchQueue;
	ISOperationQueue* _operationQueue;
	NSMutableArray* _scheduledItems;
	dispatch_source_s* _scheduledItemTimer;
}
+(id)deviceIPodLibrary;
-(void)_setDownloadPropertiesForTrack:(id)track usingLibraryItem:(id)item;
-(void)_flagDynamicContainersAsDirty;
-(void)_dispatchAsync:(id)async;
-(void)_commitScheduledLibraryItems;
-(long long)_addLibraryItem:(id)item toMusicLibrary:(id)musicLibrary error:(id*)error;
-(void)setArtworkData:(id)data forDownloadWithIdentifier:(long long)identifier;
-(void)scheduleLibraryItems:(id)items;
-(void)scheduleLibraryItem:(id)item;
-(void)removeDownloadWithIdentifier:(long long)identifier;
-(void)populateDynamicContainersIfNecessary;
-(void)deleteAllOTATracks;
-(void)commitScheduledLibraryItems;
-(BOOL)addLibraryItems:(id)items error:(id*)error;
-(long long)addLibraryItem:(id)item error:(id*)error;
-(void)dealloc;
-(id)init;
@end

