/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"
#import "NSCopying.h"

@class NSData, NSMutableDictionary, NSString, StoreDownload, NSDictionary;

__attribute__((visibility("hidden")))
@interface IPodLibraryItem : NSObject <NSCopying> {
	NSMutableDictionary* _additionalEntityProperties;
	NSData* _artworkData;
	dispatch_queue_s* _dispatchQueue;
	NSString* _downloadIdentifier;
	int _downloadType;
	long long _libraryPersistentIdentifier;
	NSString* _mediaPath;
	StoreDownload* _metadata;
	int _updateType;
}
@property(copy) NSDictionary* additionalEntityProperties;
@property(assign) int updateType;
@property(copy) StoreDownload* itemMetadata;
@property(copy) NSString* itemMediaPath;
@property(copy) NSData* itemArtworkData;
@property(assign) long long libraryPersistentIdentifier;
@property(copy) NSString* itemDownloadIdentifier;
@property(assign) int downloadType;
@property(readonly, assign, getter=isDownloading) BOOL downloading;
+(unsigned long)mediaTypeForDownloadKind:(id)downloadKind;
-(void)_updateDownloadMetadata:(id)metadata withMediaItem:(id)mediaItem;
-(void)_setValuesForImportTrack:(id)importTrack metadata:(id)metadata mapping:(PropertyMapping*)mapping count:(int)count;
-(void)_setTelevisionValuesForImportTrack:(id)importTrack metadata:(id)metadata;
-(void)_setPodcastValuesForImportTrack:(id)importTrack metadata:(id)metadata;
-(void)_setCommonValuesForImportTrack:(id)importTrack metadata:(id)metadata;
-(void)setValue:(id)value forAdditionalEntityProperty:(id)additionalEntityProperty;
-(id)copyImportTrack:(id*)track;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)init;
@end

