/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface ISFairPlayRentalInfo : NSObject {
	unsigned long _playbackDuration;
	unsigned long _playbackStartTime;
	unsigned long _rentalDuration;
	unsigned long _rentalStartTime;
}
@property(assign, nonatomic) unsigned long rentalStartTime;
@property(assign, nonatomic) unsigned long rentalDuration;
@property(assign, nonatomic) unsigned long playbackStartTime;
@property(assign, nonatomic) unsigned long playbackDuration;
@end

