/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperationQueue.h>


@interface ISOperationQueue (MicroPaymentQueueAdditions)
+(id)microPaymentQueue;
@end

