/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ISURLOperationDelegate.h"


@protocol ISStoreURLOperationDelegate <ISURLOperationDelegate>
@optional
-(BOOL)operation:(id)operation shouldSetStoreFrontID:(id)anId;
-(void)operation:(id)operation didAuthenticateWithDSID:(id)dsid;
@end

