/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

typedef struct _NSZone NSZone;

typedef struct dispatch_queue_s dispatch_queue_s;

typedef struct _xpc_connection_s xpc_connection_s;

typedef struct __CFBag* CFBagRef;

typedef struct {
	unsigned _field1[8];
} XXStruct_kUSYWB;

typedef struct DownloadChangeInfo {
	id _field1;
	int _field2;
	int _field3;
	id _field4;
	id _field5;
	id _field6;
	id _field7;
} DownloadChangeInfo;

typedef struct __CFString* CFStringRef;

typedef struct sqlite3_stmt sqlite3_stmt;

typedef struct SBSProcessAssertion* SBSProcessAssertionRef;

typedef struct dispatch_source_s dispatch_source_s;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct dispatch_semaphore_s dispatch_semaphore_s;

typedef struct PropertyMapping {
	SEL _field1;
	id _field2;
	/*function-pointer*/ void* _field3;
} PropertyMapping;

typedef struct DeviceContext {
	BOOL _field1;
	id _field2;
} DeviceContext;

typedef struct __CFUserNotification* CFUserNotificationRef;

typedef struct __CFRunLoopSource* CFRunLoopSourceRef;


