/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface KeyValueObserverItem : NSObject {
	id _block;
	NSString* _keyPath;
	id _object;
}
@property(readonly, assign, nonatomic) id object;
@property(readonly, assign, nonatomic) NSString* keyPath;
@property(readonly, assign, nonatomic) id block;
-(void)dealloc;
-(id)initWithObject:(id)object keyPath:(id)path block:(id)block;
@end

