/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RequestQueueOperation.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface LoadMicroPaymentProductsOperation : RequestQueueOperation {
	NSArray* _invalidIdentifiers;
	NSArray* _productIdentifiers;
	NSArray* _products;
}
@property(retain) NSArray* products;
@property(retain) NSArray* invalidIdentifiers;
@property(retain) NSArray* productIdentifiers;
-(BOOL)_loadResponseForApplication:(id)application batchSize:(int)size returningError:(id*)error;
-(id)_copyQueryStringDictionaryForApplication:(id)application productIdentifiers:(id)identifiers;
-(id)_copyResponseForApplication:(id)application identifiers:(id)identifiers returningError:(id*)error;
-(int)_getBatchSizeWithError:(id*)error;
-(id)_getApplicationWithError:(id*)error;
-(int)_bagType;
-(void)_clientStoppedNotification:(id)notification;
-(void)run;
-(id)copyResponseDictionary;
-(void)dealloc;
@end

