/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ISOperationDelegate.h"


@protocol LoadCompletedMicroPaymentsDelegate <ISOperationDelegate>
-(void)operation:(id)operation loadedPaymentsBatch:(id)batch;
@end

