/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class MicroPaymentQueueRequest, MicroPaymentQueueResponse, NSString;

__attribute__((visibility("hidden")))
@interface LoadMicroPaymentQueueOperation : ISOperation {
	int _expectedCount;
	NSString* _queueCountURLBagKey;
	NSString* _queuePaymentsURLBagKey;
	MicroPaymentQueueRequest* _request;
	MicroPaymentQueueResponse* _response;
}
@property(retain) MicroPaymentQueueResponse* response;
@property(copy) MicroPaymentQueueRequest* request;
@property(retain) NSString* queuePaymentsURLBagKey;
@property(retain) NSString* queueCountURLBagKey;
@property(assign) int expectedCount;
-(BOOL)_loadPaymentsWithExpectedCount:(int)expectedCount error:(id*)error;
-(BOOL)_getQueueCount:(int*)count error:(id*)error;
-(void)run;
-(void)dealloc;
@end

