/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class MicroPaymentQueueRequest, MicroPaymentQueueResponse, NSString;

__attribute__((visibility("hidden")))
@interface LoadMicroPaymentQueuePaymentsOperation : ISOperation {
	MicroPaymentQueueRequest* _request;
	MicroPaymentQueueResponse* _response;
	NSString* _urlBagKey;
}
@property(retain) MicroPaymentQueueResponse* response;
@property(retain) NSString* URLBagKey;
@property(copy) MicroPaymentQueueRequest* request;
-(BOOL)_parsePropertyList:(id)list error:(id*)error;
-(BOOL)_loadResponseReturningError:(id*)error;
-(BOOL)_appendRangeRequestsToResponse:(id)response error:(id*)error;
-(void)run;
-(void)dealloc;
@end

