/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSNumber, NSOrderedSet, NSString, NSMutableArray, SSURLRequestProperties, ClientIdentity, NSMutableOrderedSet;

__attribute__((visibility("hidden")))
@interface LoadDownloadQueueOperation : ISOperation {
	NSNumber* _accountIdentifier;
	ClientIdentity* _clientIdentity;
	NSMutableOrderedSet* _downloads;
	BOOL _needsAuthentication;
	NSMutableArray* _rangesToLoad;
	int _reason;
	NSString* _requestIdentifier;
	SSURLRequestProperties* _requestProperties;
}
@property(readonly, assign) NSOrderedSet* downloads;
@property(copy) NSString* requestIdentifier;
@property(assign) int reason;
@property(assign) BOOL needsAuthentication;
@property(retain) ClientIdentity* clientIdentity;
@property(retain) NSNumber* accountIdentifier;
@property(readonly, assign) SSURLRequestProperties* requestProperties;
+(id)newLoadAutomaticDownloadQueueOperation;
-(BOOL)_shouldSendKeyBagSync;
-(id)_newURLOperationWithStartIdentifier:(id)startIdentifier endIdentifier:(id)identifier;
-(BOOL)_loadDownloadsFromStart:(id)start toEnd:(id)end;
-(void)_handleResponse:(id)response;
-(id)_account;
-(void)run;
-(void)dealloc;
-(id)initWithRequestProperties:(id)requestProperties;
-(id)init;
@end

