/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSString, NSArray, SSSoftwareUpdatesContext, NSURL;

__attribute__((visibility("hidden")))
@interface LoadUpdateQueueOperation : ISOperation {
	SSSoftwareUpdatesContext* _context;
	NSArray* _updates;
	NSURL* _url;
	NSString* _urlBagKey;
}
@property(retain) NSArray* updates;
@property(retain) NSString* URLBagKey;
@property(retain) NSURL* URL;
@property(readonly, assign) SSSoftwareUpdatesContext* softwareUpdatesContext;
-(id)_requestBodyData:(BOOL*)data;
-(void)run;
-(void)dealloc;
-(id)initWithSoftwareUpdatesContext:(id)softwareUpdatesContext;
-(id)init;
@end

