/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class MicroPaymentQueueRequest, NSString;

__attribute__((visibility("hidden")))
@interface LoadMicroPaymentQueueCountOperation : ISOperation {
	int _queueItemCount;
	MicroPaymentQueueRequest* _request;
	NSString* _urlBagKey;
}
@property(assign) int queueItemCount;
@property(retain) NSString* URLBagKey;
@property(copy) MicroPaymentQueueRequest* request;
-(BOOL)_setCountWithResponse:(id)response error:(id*)error;
-(BOOL)_loadCountReturningError:(id*)error;
-(void)run;
-(void)dealloc;
@end

