/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>
#import "ISStoreURLOperationDelegate.h"

@class ClientIdentity;
@protocol LoadCompletedMicroPaymentsDelegate;

__attribute__((visibility("hidden")))
@interface LoadCompletedMicroPaymentsOperation : ISOperation <ISStoreURLOperationDelegate> {
	ClientIdentity* _clientIdentity;
	BOOL _partialFailure;
}
@property(assign, getter=isPartialFailure) BOOL partialFailure;
@property(retain) ClientIdentity* clientIdentity;
@property(assign) id<LoadCompletedMicroPaymentsDelegate> delegate;
-(void)_sendQueueResponseToDelegate:(id)delegate;
-(void)_runForApplication:(id)application;
-(id)_newFetchOperationForApplication:(id)application startID:(id)anId endID:(id)anId3;
-(id)_copyResponseForApplication:(id)application startID:(id)anId endID:(id)anId3 returningError:(id*)error;
-(void)run;
-(void)dealloc;
@end

