/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol MBManagerDelegate
@optional
-(void)managerDidLoseConnectionToService:(id)manager;
-(void)manager:(id)manager didFailRestoreWithError:(id)error;
-(void)manager:(id)manager didFailScanWithError:(id)error;
-(void)manager:(id)manager didFailBackupWithError:(id)error;
-(void)managerDidCancelRestore:(id)manager;
-(void)managerDidFinishRestore:(id)manager;
-(void)managerDidFinishScan:(id)manager;
-(void)managerDidFinishBackup:(id)manager;
-(void)manager:(id)manager didUpdateProgress:(float)progress estimatedTimeRemaining:(unsigned)remaining;
-(void)manager:(id)manager didSetBackupEnabled:(BOOL)enabled;
@end

