/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface MediaDRMOperation : ISOperation {
	NSString* _mediaFileExtension;
	NSString* _mediaPath;
	id _sinfs;
}
@property(readonly, assign) NSString* mediaFileExtension;
@property(readonly, assign) id sinfs;
@property(readonly, assign) NSString* mediaPath;
-(void)run;
-(void)dealloc;
-(id)initWithMediaPath:(id)mediaPath sinfs:(id)sinfs;
@end

