/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface MediaItem : NSObject {
	NSArray* _chapters;
	double _duration;
	int _type;
}
@property(assign, nonatomic) int type;
@property(assign, nonatomic) double durationInSeconds;
@property(retain, nonatomic) NSArray* chapters;
-(id)_copyChapterVideoTracksForAsset:(id)asset;
-(void)dealloc;
-(id)initWithPath:(id)path;
@end

