/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import <Foundation/NSObject.h>

@class MessageServer;

__attribute__((visibility("hidden")))
@interface MessageServerReceiver : NSObject {
	MessageServer* _messageServer;
}
-(void)_unregisterDistributedNotificationObserver:(void*)observer connection:(xpc_connection_s*)connection;
-(void)_triggerDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)_setDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)_setDownloadProperties:(void*)properties connection:(xpc_connection_s*)connection;
-(void)_setDownloadHandlerStatusDescription:(void*)description connection:(xpc_connection_s*)connection;
-(void)_setDownloadHandlerSessionProperties:(void*)properties connection:(xpc_connection_s*)connection;
-(void)_setDownloadHandlerProperties:(void*)properties connection:(xpc_connection_s*)connection;
-(void)_setDownloadHandlerPercentComplete:(void*)complete connection:(xpc_connection_s*)connection;
-(void)_setDownloadHandler:(void*)handler connection:(xpc_connection_s*)connection;
-(void)_setClientDownloadHandler:(void*)handler connection:(xpc_connection_s*)connection;
-(void)_setAssetProperties:(void*)properties connection:(xpc_connection_s*)connection;
-(void)_retryRestoreDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)_resumeDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)_resetDisavowedSessions:(void*)sessions connection:(xpc_connection_s*)connection;
-(void)_removePurchaseManifestItem:(void*)item connection:(xpc_connection_s*)connection;
-(void)_removeDownloadManagerPersistenceID:(void*)anId connection:(xpc_connection_s*)connection;
-(void)_reloadDownloadManager:(void*)manager connection:(xpc_connection_s*)connection;
-(void)_registerPreorderManager:(void*)manager connection:(xpc_connection_s*)connection;
-(void)_registerEventMonitor:(void*)monitor connection:(xpc_connection_s*)connection;
-(void)_registerDownloadManager:(void*)manager connection:(xpc_connection_s*)connection;
-(void)_registerDownloadHandler:(void*)handler connection:(xpc_connection_s*)connection;
-(void)_registerDistributedNotificationObserver:(void*)observer connection:(xpc_connection_s*)connection;
-(void)_reevaluateBackgroundDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)_rebuildPurchaseManifest:(void*)manifest connection:(xpc_connection_s*)connection;
-(void)_purchaseRequest:(void*)request connection:(xpc_connection_s*)connection;
-(void)_prioritizeDownload:(void*)download connection:(xpc_connection_s*)connection;
-(void)_pauseDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)_moveDownload:(void*)download connection:(xpc_connection_s*)connection;
-(void)_mobileInstallationLookup:(void*)lookup connection:(xpc_connection_s*)connection;
-(void)_loadURLBag:(void*)bag connection:(xpc_connection_s*)connection;
-(void)_invalidateURLBag:(void*)bag connection:(xpc_connection_s*)connection;
-(void)_loadDownloadThumbnail:(void*)thumbnail connection:(xpc_connection_s*)connection;
-(void)_insertDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)_getPurchaseManifestPaths:(void*)paths connection:(xpc_connection_s*)connection;
-(void)_getPreorders:(void*)preorders connection:(xpc_connection_s*)connection;
-(void)_getEntityExists:(void*)exists connection:(xpc_connection_s*)connection;
-(void)_getDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)_getDownloadProperties:(void*)properties connection:(xpc_connection_s*)connection;
-(void)_getDownloadHandlerSessionProperties:(void*)properties connection:(xpc_connection_s*)connection;
-(void)_getDownloadKindsUsingNetwork:(void*)network connection:(xpc_connection_s*)connection;
-(void)_getDownloadAssets:(void*)assets connection:(xpc_connection_s*)connection;
-(void)_getDownloadAssetProperties:(void*)properties connection:(xpc_connection_s*)connection;
-(void)_getActiveDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)_finishDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)_finishDownloadSession:(void*)session connection:(xpc_connection_s*)connection;
-(void)_deleteIPodPurchases:(void*)purchases connection:(xpc_connection_s*)connection;
-(void)_checkPreorderQueue:(void*)queue connection:(xpc_connection_s*)connection;
-(void)_cancelPreorders:(void*)preorders connection:(xpc_connection_s*)connection;
-(void)_cancelDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)_cancelAllDownloads:(void*)downloads connection:(xpc_connection_s*)connection;
-(void)_unregisterForRemoteNotifications:(id)remoteNotifications userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_syncAutoDownloadKinds:(id)kinds userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_showLocalNotification:(id)notification userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_setRequestGroup:(id)group userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_restoreStoreKitCompletedTransactions:(id)transactions userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_requestStoreKitProducts:(id)products userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_registerForRemoteNotifications:(id)remoteNotifications userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_finishPayment:(id)payment userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_disconnectStoreServicesRequest:(id)request userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_checkOutPaymentClient:(id)client userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_checkInPaymentClient:(id)paymentClient userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_cancelStoreServicesRequest:(id)request userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_cancelStoreKitRequest:(id)request userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_addPaymentRequest:(id)request userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(id)_signOut:(id)anOut userInfo:(id)info;
-(id)_setAccountCredits:(id)credits userInfo:(id)info;
-(void)_showPrompt:(id)prompt userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_setAutomaticDownloadKinds:(id)kinds userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_personalizeOffers:(id)offers userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_lookupItems:(id)items userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_loadURLBag:(id)bag userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(id)_getRequestsInGroup:(id)group userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(id)_getRequestIsRunning:(id)running userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_getPlayInfo:(id)info userInfo:(id)info2 auditToken:(XXStruct_kUSYWB*)token;
-(void)_getAccountPurchaseHistory:(id)history userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(id)_getRemoteNotifications:(id)notifications userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_getAvailableItemKinds:(id)kinds userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(id)_getAccountAuthenticated:(id)authenticated userInfo:(id)info;
-(id)_getAccounts:(id)accounts userInfo:(id)info;
-(id)_getAutomaticDownloadKinds:(id)kinds userInfo:(id)info;
-(void)_checkUpdateQueue:(id)queue userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_checkOutRental:(id)rental userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_checkInRental:(id)rental userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_authorizeMachine:(id)machine userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_authenticateRequest:(id)request userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_addURLRequest:(id)request userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_addPurchases:(id)purchases userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(void)_addDownloadsUsingManifest:(id)manifest userInfo:(id)info auditToken:(XXStruct_kUSYWB*)token;
-(id)_addAccount:(id)account userInfo:(id)info;
-(BOOL)shouldStayAlive;
-(void)runWithMessageServer:(id)messageServer;
-(void)dealloc;
@end

