/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"

@class NSMutableSet, NSMutableArray, NSCountedSet;

__attribute__((visibility("hidden")))
@interface MessageServer : NSObject {
	NSMutableArray* _backgroundTaskAgentNotifications;
	dispatch_queue_s* _dispatchQueue;
	NSCountedSet* _keepAliveAssertions;
	NSMutableSet* _keepAliveOperationQueues;
	id _receiver;
	id _stopHandler;
	CFBagRef _wakeupReasons;
}
+(id)sharedMessageServer;
-(void)_restoreStoreKitCompletedTransactions:(id)transactions userInfo:(id)info client:(id)client;
-(void)_requestStoreKitProducts:(id)products userInfo:(id)info client:(id)client;
-(void)_finishPayment:(id)payment userInfo:(id)info client:(id)client;
-(void)_checkOutPaymentClient:(id)client userInfo:(id)info client:(id)client3;
-(void)_checkInPaymentClient:(id)paymentClient userInfo:(id)info client:(id)client;
-(void)_cancelStoreKitRequest:(id)request userInfo:(id)info client:(id)client;
-(void)_addPaymentRequest:(id)request userInfo:(id)info client:(id)client;
-(void)_setStoreFront:(id)front userInfo:(id)info;
-(void)_setRequestGroup:(id)group userInfo:(id)info client:(id)client;
-(void)_scheduleReview:(id)review userInfo:(id)info;
-(void)_resetAccount:(id)account userInfo:(id)info;
-(void)_disconnectStoreServicesRequest:(id)request userInfo:(id)info client:(id)client;
-(void)_cancelStoreServicesRequest:(id)request userInfo:(id)info client:(id)client;
-(id)_stopHandler;
-(BOOL)_shouldKeepAlive;
-(void)_removeJobForWakeupReason:(int)wakeupReason;
-(void)_observeBackgroundTaskAgent;
-(char*)_jobNameForWakeupReason:(int)wakeupReason;
-(void)_addJobForWakeupReason:(int)wakeupReason;
-(void)_pluggedInChanged:(id)changed;
-(void)_networkTypeChanged:(id)changed;
-(void)takeKeepAliveAssertion:(id)assertion;
-(BOOL)startWithStopHandler:(id)stopHandler;
-(void)requestWakeupWithReason:(int)reason;
-(void)requestWakeupWithJob:(void*)job notificationName:(id)name;
-(void)removeKeepAliveOperationQueue:(id)queue;
-(void)releaseKeepAliveAssertion:(id)assertion;
-(void)keepAliveWithAssertion:(id)assertion block:(id)block;
-(void)cancelWakeupRequestWithReason:(int)reason;
-(void)cancelAllWakeupRequestsWithReason:(int)reason;
-(void)beginDeliveringBackgroundTaskAgentNotifications;
-(void)addKeepAliveOperationQueue:(id)queue;
-(void)dealloc;
-(id)init;
@end

