/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface MicroPaymentProductsResponse : NSObject {
	NSArray* _expectedIdentifiers;
	NSArray* _invalidIdentifiers;
	NSArray* _products;
}
@property(retain, nonatomic) NSArray* products;
@property(retain, nonatomic) NSArray* invalidIdentifiers;
@property(retain, nonatomic) NSArray* expectedIdentifiers;
-(BOOL)loadFromDictionary:(id)dictionary returningError:(id*)error;
-(void)dealloc;
@end

