/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface MicroPaymentProduct : NSObject {
	NSString* _localeIdentifier;
	NSString* _localizedDescription;
	NSString* _localizedTitle;
	NSNumber* _price;
	NSString* _productIdentifier;
}
@property(retain, nonatomic) NSString* productIdentifier;
@property(retain, nonatomic) NSNumber* price;
@property(retain, nonatomic) NSString* localizedTitle;
@property(retain, nonatomic) NSString* localizedDescription;
@property(retain, nonatomic) NSString* localeIdentifier;
-(id)copyPropertyListRepresentation;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary;
@end

