/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "ISOperationDelegate.h"
#import "ISSingleton.h"

@class MicroPayment, NSManagedObjectContext;

__attribute__((visibility("hidden")))
@interface MicroPaymentQueue : NSObject <ISOperationDelegate, ISSingleton> {
	MicroPayment* _activePayment;
	int _changeSetCount;
	NSManagedObjectContext* _context;
}
+(BOOL)canMakePayments;
+(id)sharedInstance;
+(void)setSharedInstance:(id)instance;
-(void)_showPaymentsRestrictedAlert;
-(void)_setActivePayment:(id)payment;
-(void)_sendError:(id)error forProductID:(id)productID quantity:(id)quantity toClientWithIdentity:(id)identity;
-(id)_firstReadyPayment;
-(void)_networkTypeChanged:(id)changed;
-(void)_mainThreadNetworkTypeChanged:(id)changed;
-(void)_clientRefreshedFromServer:(id)server;
-(void)operationFinished:(id)finished;
-(void)operation:(id)operation failedWithError:(id)error;
-(void)operation:(id)operation didChangeState:(int)state;
-(void)restoreCompletedTransactionsWithInfo:(id)info identity:(id)identity;
-(void)finishRefundWithInfo:(id)info identity:(id)identity;
-(void)finishPaymentWithInfo:(id)info identity:(id)identity;
-(void)checkOutClientWithInfo:(id)info identity:(id)identity;
-(void)checkInClientWithInfo:(id)info identity:(id)identity;
-(void)addPaymentWithInfo:(id)info identity:(id)identity;
-(BOOL)startFirstReadyPayment;
-(BOOL)checkQueues;
-(void)dealloc;
-(id)init;
@end

