/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class MicroPaymentClient, NSMutableArray, NSEntityDescription, NSArray;

__attribute__((visibility("hidden")))
@interface MicroPaymentClientResponseHandler : NSObject {
	NSMutableArray* _addedPayments;
	NSMutableArray* _changedPayments;
	MicroPaymentClient* _client;
	NSEntityDescription* _entity;
	NSArray* _existingPayments;
	NSMutableArray* _removedPayments;
}
@property(readonly, assign, nonatomic) NSArray* removedPayments;
@property(readonly, assign, nonatomic) NSArray* changedPayments;
@property(readonly, assign, nonatomic) NSArray* addedPayments;
@property(retain, nonatomic) NSArray* existingPayments;
@property(retain, nonatomic) NSEntityDescription* entity;
@property(readonly, assign, nonatomic) MicroPaymentClient* client;
-(void)_removeUnmergedPayments:(id)payments;
-(void)mergeResponse:(id)response withOptions:(int)options;
-(void)dealloc;
-(id)initWithMicroPaymentClient:(id)microPaymentClient;
-(id)init;
@end

