/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableArray, NSLock, NSArray;

__attribute__((visibility("hidden")))
@interface MicroPaymentQueueResponse : NSObject {
	NSLock* _lock;
	NSMutableArray* _payments;
	NSMutableArray* _rangesToLoad;
	int _requestType;
	int _serverPaymentCount;
	BOOL _shouldTriggerQueueCheck;
}
@property(assign) BOOL shouldTriggerQueueCheck;
@property(assign) int serverPaymentCount;
@property(retain) NSArray* rangesToLoad;
@property(copy) NSArray* payments;
@property(readonly, assign) int requestType;
-(BOOL)_ntsLoadFromPropertyList:(id)propertyList;
-(id)_dsidFromDictionary:(id)dictionary;
-(id)_copyPaymentsFromDictionary:(id)dictionary;
-(BOOL)loadFromPropertyList:(id)propertyList;
-(void)appendResponse:(id)response;
-(void)dealloc;
-(id)initWithRequestType:(int)requestType;
@end

