/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSThread.h>


@interface NSThread (CoreDataAdditions)
+(void)endPrivateManagedContextSession;
+(void)endManagedContextSession;
+(id)beginPrivateManagedContextSession;
+(id)beginManagedContextSession;
@end

