/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SQLiteEntity.h"


__attribute__((visibility("hidden")))
@interface PersistentDownloadManager : SQLiteEntity {
}
+(void)initialize;
+(id)foreignKeyColumnForTable:(id)table;
+(id)foreignDatabaseTablesToDelete;
+(id)databaseTable;
@end

