/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, NSManagedObjectModel, NSPersistentStoreCoordinator, PersistentStoreConfiguration, NSURL;

__attribute__((visibility("hidden")))
@interface PersistentStore : NSObject {
	PersistentStoreConfiguration* _configuration;
	NSManagedObjectModel* _model;
	NSPersistentStoreCoordinator* _storeCoordinator;
	NSString* _threadContextKey;
	NSString* _threadCountKey;
}
@property(readonly, assign) NSURL* modelFileURL;
@property(readonly, assign) NSURL* databaseFileURL;
@property(readonly, assign) PersistentStoreConfiguration* configuration;
-(id)_newLegacyManagedObjectModel;
-(BOOL)_loadStoreCoordinatorWithIntegrityCheck:(BOOL)integrityCheck error:(id*)error;
-(id)_baseFilePath;
-(id)managedObjectModel;
-(BOOL)loadStoreCoordinatorWithOptions:(id)options error:(id*)error;
-(BOOL)resetStore:(id*)store;
-(BOOL)performLightweightMigration:(id*)migration;
-(void)endThreadContextSession;
-(void)checkIntegrityWithInitializationBlock:(id)initializationBlock;
-(id)beginThreadContextSession;
-(void)dealloc;
-(id)initWithConfiguration:(id)configuration error:(id*)error;
-(id)init;
@end

