/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSData, SSAuthenticationContext, NSString;

__attribute__((visibility("hidden")))
@interface PostPushNotificationTokenOperation : ISOperation {
	SSAuthenticationContext* _authenticationContext;
	NSString* _environmentName;
	NSData* _tokenData;
}
@property(copy) SSAuthenticationContext* authenticationContext;
@property(readonly, assign) NSData* tokenData;
@property(readonly, assign) NSString* environmentName;
-(BOOL)_postTokenToURL:(id)url error:(id*)error;
-(void)run;
-(void)dealloc;
-(id)initWithEnvironmentName:(id)environmentName tokenData:(id)data;
-(id)init;
@end

