/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>


__attribute__((visibility("hidden")))
@interface PostRatingOperation : ISOperation {
	unsigned long long _itemIdentifier;
	float _rating;
	unsigned _versionIdentifier;
}
@property(assign) unsigned versionIdentifier;
@property(assign) float rating;
@property(assign) unsigned long long itemIdentifier;
+(void)watchForAuthentication;
+(BOOL)scheduleRatingWithValue:(float)value forItem:(unsigned long long)item version:(unsigned)version;
+(BOOL)scheduleRatingWithInfo:(id)info;
+(void)performScheduledRatings;
+(void)_accountAuthorizedNotification:(id)notification;
-(void)run;
-(id)initWithRating:(float)rating forItem:(unsigned long long)item;
@end

