/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SQLiteEntity.h"


__attribute__((visibility("hidden")))
@interface Preorder : SQLiteEntity {
}
+(id)newValueDictionaryWithItem:(id)item;
+(id)newClientPreorderWithPersistentID:(long long)persistentID allValues:(id*)values;
+(id)allProperties;
+(id)databaseTable;
-(void)setValuesWithItem:(id)item;
@end

