/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ISOperationDelegate.h"
#import "DownloadAssetOperation.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface ProcessAssetOperation : DownloadAssetOperation <ISOperationDelegate> {
	NSMutableArray* _steps;
}
-(void)_setProgress:(double)progress forOperation:(id)operation;
-(id)_newUnprotectMediaStepWithLocalPath:(id)localPath storeDownload:(id)download;
-(id)_newDecryptEBookStepWithStoreDownload:(id)storeDownload;
-(id)_newCheckoutRentalKeysStepWithDownload:(id)download storeDownload:(id)download2;
-(id)_newCheckHashesStepWithLocalPath:(id)localPath hashArrayData:(id)data bytesToHash:(long long)hash;
-(void)operationFinished:(id)finished;
-(void)operation:(id)operation updatedProgress:(id)progress;
-(void)run;
-(void)dealloc;
@end

