/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface PurchaseManifestItem : NSObject {
	NSMutableDictionary* _dictionary;
}
@property(readonly, assign, nonatomic) NSDictionary* manifestItemDictionary;
@property(copy, nonatomic) NSString* relativeMetadataPath;
@property(copy, nonatomic) NSString* relativeMediaAssetPath;
@property(copy, nonatomic) NSString* relativeFeedAssetPath;
@property(copy, nonatomic) NSString* relativeArtworkPath;
-(void)_setValue:(id)value forKey:(id)key;
-(void)dealloc;
-(id)initWithManifestItemDictionary:(id)manifestItemDictionary;
-(id)init;
@end

