/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"

@class NSMutableDictionary, NSString, NSArray;

__attribute__((visibility("hidden")))
@interface PurchaseManifest : NSObject {
	NSMutableDictionary* _dictionary;
	dispatch_queue_s* _dispatchQueue;
	NSString* _path;
}
@property(readonly, assign) NSArray* purchaseManifestItems;
@property(readonly, assign) NSString* path;
+(id)_sharedManifestWithManifestType:(int)manifestType;
+(void)_handleMessage:(void*)message connection:(xpc_connection_s*)connection usingBlock:(id)block;
+(void)removeItemWithMessage:(void*)message connection:(xpc_connection_s*)connection;
+(void)rebuildWithMessage:(void*)message connection:(xpc_connection_s*)connection;
+(void)getPathsWithMessage:(void*)message connection:(xpc_connection_s*)connection;
+(id)sharedManifestForDownloadKind:(id)downloadKind;
+(void)jetsam;
-(BOOL)_writeToFile;
-(id)_dictionary;
-(id)removeItemsWithAssetPaths:(id)assetPaths error:(id*)error;
-(void)rebuildManifest;
-(void)jetsam;
-(void)addCompletedItem:(id)item;
-(void)dealloc;
-(id)initWithPurchaseDirectory:(id)purchaseDirectory;
-(id)init;
@end

