/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>
#import "ISDialogOperationDelegate.h"
#import "ISStoreURLOperationDelegate.h"

@class NSNumber, SSURLRequestProperties, SSAuthenticationContext, NSString, ClientIdentity, NSDictionary;

__attribute__((visibility("hidden")))
@interface PurchaseOperation : ISOperation <ISDialogOperationDelegate, ISStoreURLOperationDelegate> {
	NSNumber* _accountID;
	SSAuthenticationContext* _authenticationContext;
	int _bagType;
	NSString* _buyParameters;
	ClientIdentity* _clientIdentity;
	BOOL _displayedErrorDialog;
	NSString* _downloadKind;
	BOOL _isBackgroundPurchase;
	BOOL _needsAuthentication;
	BOOL _partOfBatchPurchase;
	NSDictionary* _rawOutput;
	SSURLRequestProperties* _requestProperties;
	id _responseInfo;
	BOOL _shouldSendKeyBagSyncData;
	NSString* _urlBagKey;
}
@property(retain) NSDictionary* rawOutput;
@property(assign) BOOL displayedErrorDialog;
@property(retain) NSString* urlBagKey;
@property(assign) BOOL shouldSendKeyBagSyncData;
@property(assign) BOOL needsAuthentication;
@property(assign, getter=isPartOfBatchPurchase) BOOL partOfBatchPurchase;
@property(assign, getter=isBackgroundPurchase) BOOL backgroundPurchase;
@property(retain) ClientIdentity* clientIdentity;
@property(retain) NSString* buyParameters;
@property(assign) int bagType;
@property(copy) SSAuthenticationContext* authenticationContext;
-(BOOL)_shouldSendKeyBagSyncData;
-(void)_runPurchaseRequest;
-(void)_runDialogOperationForDialog:(id)dialog;
-(id)_requestBodyDataForBuyParameters:(id)buyParameters;
-(void)_handleFailureResponse:(id)response forOperation:(id)operation;
-(void)_addKeyBagSyncDataForOperation:(id)operation accountID:(unsigned long long)anId;
-(id)_account;
-(void)operation:(id)operation selectedButton:(id)button;
-(void)operation:(id)operation didAuthenticateWithDSID:(id)dsid;
-(void)run;
-(id)authenticatedAccountDSID;
-(void)dealloc;
-(id)initWithPurchase:(id)purchase;
-(id)init;
@end

