/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class SSRemoteNotification, NSDictionary;

__attribute__((visibility("hidden")))
@interface PushNotificationDisplayOperation : ISOperation {
	SSRemoteNotification* _notification;
}
@property(readonly, assign) BOOL requiresClientIdentifier;
@property(readonly, assign) NSDictionary* notificationUserInfo;
-(void)_playSound;
-(void)_performNotificationAction:(BOOL)action;
-(void)_openNotificationURL;
-(int)_notificationClass;
-(void)_loadNotificationDownloadManifest;
-(void)_displayBadge;
-(void)_displayAlert;
-(id)_copyAlertTitle;
-(id)_clientIdentifierForDownloadKinds:(id)downloadKinds;
-(void)run;
-(void)dealloc;
-(id)initWithNotificationUserInfo:(id)notificationUserInfo;
-(id)init;
@end

