/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <CoreData/NSManagedObject.h>

@class NSData, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface PushNotificationEnvironment : NSManagedObject {
}
@property(copy, nonatomic) NSData* tokenData;
@property(retain, nonatomic) NSNumber* lastAccountIdentifier;
@property(copy, nonatomic) NSString* environmentName;
+(id)entityFromContext:(id)context;
@end

