/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>


__attribute__((visibility("hidden")))
@interface PushNotificationSoundsSyncOperation : ISOperation {
}
-(id)_newSoundFileURLCache;
-(BOOL)_downloadSoundFiles:(id)files error:(id*)error;
-(BOOL)_downloadSoundFileWithURL:(id)url name:(id)name cache:(id)cache error:(id*)error;
-(void)run;
@end

