/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <CoreData/NSManagedObject.h>

@class NSData, PushNotificationClient;

__attribute__((visibility("hidden")))
@interface PushNotification : NSManagedObject {
}
@property(copy, nonatomic) NSData* userInfo;
@property(retain, nonatomic) PushNotificationClient* client;
+(id)entityFromContext:(id)context;
@end

