/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class XPCClient, NSString, ClientIdentity;

__attribute__((visibility("hidden")))
@interface RequestQueueOperation : ISOperation {
	XPCClient* _client;
	ClientIdentity* _clientIdentity;
	BOOL _disconnected;
	NSString* _requestGroupIdentifier;
	NSString* _requestIdentifier;
}
@property(retain) NSString* requestIdentifier;
@property(retain) NSString* requestGroupIdentifier;
@property(assign, getter=isClientConnected) BOOL clientConnected;
@property(retain) ClientIdentity* clientIdentity;
@property(retain) XPCClient* client;
-(id)copyResponseDictionary;
-(id)copyRequest;
-(void)dealloc;
-(id)initWithRequest:(id)request;
@end

