/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RequestQueueOperation.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface RequestQueueArrayOperation : RequestQueueOperation {
	NSArray* _operations;
	BOOL _shouldContinueAfterFailure;
}
@property(assign) BOOL shouldContinueAfterFailure;
@property(readonly, assign) NSArray* operations;
-(void)run;
-(void)dealloc;
-(id)initWithOperations:(id)operations;
-(id)init;
@end

