/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RequestQueueOperation.h"


__attribute__((visibility("hidden")))
@interface RequestQueueDecoratorOperation : RequestQueueOperation {
	ISOperation* _operation;
	id _requestProviderBlock;
	id _responseProviderBlock;
}
@property(copy) id responseProviderBlock;
@property(copy) id requestProviderBlock;
@property(retain) ISOperation* operation;
-(void)run;
-(id)copyResponseDictionary;
-(id)copyRequest;
-(void)dealloc;
@end

