/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface RestoreStatistics : NSObject {
}
+(void)_addUniqueValue:(id)value withDefaultsKey:(CFStringRef)defaultsKey aggregateKey:(id)key;
+(void)_addScalarValue:(long long)value forKey:(id)key;
+(void)_addFailureWithKind:(id)kind downloadKind:(id)kind2 error:(id)error;
+(void)addTransferFailureWithKind:(id)kind error:(id)error;
+(void)addSuccessfulRestoreWithKind:(id)kind;
+(void)addStoreFrontWithStoreFrontID:(id)storeFrontID;
+(void)addSoftFailureWithKind:(id)kind error:(id)error;
+(void)addItemsWithKind:(id)kind count:(int)count;
+(void)addInstallFailureWithKind:(id)kind error:(id)error;
+(void)addHardFailureWithKind:(id)kind error:(id)error;
+(void)addDataRestoreFailureWithKind:(id)kind error:(id)error;
+(void)addAccountWithAccountID:(id)accountID;
@end

