/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSMutableArray, SSAccount, NSArray;
@protocol RestoreDownloadItemsOperationDelegate;

__attribute__((visibility("hidden")))
@interface RestoreDownloadItemsOperation : ISOperation {
	SSAccount* _account;
	NSArray* _downloadItems;
	NSMutableArray* _responses;
	BOOL _shouldShowTermsAndConditionsDialog;
}
@property(readonly, assign) NSArray* responses;
@property(assign) BOOL shouldShowTermsAndConditionsDialog;
@property(assign) id<RestoreDownloadItemsOperationDelegate> delegate;
@property(readonly, assign) NSArray* downloadItems;
@property(readonly, assign) SSAccount* account;
-(void)_showDialogsForResponse:(id)response;
-(BOOL)_runWithOptions:(id)options error:(id*)error;
-(id)_runWithItems:(id)items options:(id)options;
-(id)_runWithBodyData:(id)bodyData contentEncoding:(id)encoding options:(id)options error:(id*)error;
-(void)_run;
-(id)_plistDataWithItems:(id)items options:(id)options error:(id*)error;
-(id)_newResponseWithItems:(id)items error:(id)error;
-(void)_addResponse:(id)response;
-(void)run;
-(void)dealloc;
-(id)initWithDownloadItems:(id)downloadItems account:(id)account;
@end

