/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>
#import "itunesstored-Structs.h"
#import "RestoreDownloadItemsOperationDelegate.h"

@class NSMutableDictionary, NSOrderedSet, NSString, NSMutableArray, NSArray;

__attribute__((visibility("hidden")))
@interface RestoreDownloadsOperation : ISOperation <RestoreDownloadItemsOperationDelegate> {
	NSMutableDictionary* _accountIDsByAppleID;
	int _cancelRetryAlertState;
	NSOrderedSet* _downloadIDs;
	NSMutableArray* _errors;
	BOOL _hadAutoRetrySoftFailure;
	BOOL _hadCancelFailure;
	BOOL _hadHardFailure;
	NSString* _restoreReason;
}
@property(readonly, assign) NSArray* errors;
@property(readonly, assign) NSString* restoreReason;
@property(readonly, assign) NSOrderedSet* downloadIdentifiers;
+(BOOL)shouldSuppressTermsAndConditionsDialogs;
+(void)setShouldSuppressTermsAndConditionsDialogs:(BOOL)suppressTermsAndConditionsDialogs;
+(void)resetShouldSuppressTermsAndConditionsDialogs;
-(BOOL)_shouldAutomaticallyRetryAfterSoftFailError:(id)error;
-(BOOL)_shouldAuthenticateForCancelRetry;
-(void)_scheduleCancelRetry;
-(void)_scheduleAutomaticRetry;
-(BOOL)_preflightAccountWithID:(id)anId error:(id*)error;
-(id)_newImportDownloadWithStoreDownload:(id)storeDownload;
-(BOOL)_isErrorSoftFail:(id)fail;
-(BOOL)_isErrorCancelFailure:(id)failure;
-(void)_hardFailRestoreItem:(id)item download:(id)download changeInfo:(DownloadChangeInfo*)info error:(id)error;
-(void)_establishPrimaryAccount;
-(void)_applyResponses:(id)responses withDatabase:(id)database changeInfo:(DownloadChangeInfo*)info;
-(id)_accountIDForAccountName:(id)accountName error:(id*)error;
-(void)restoreDownloadItemsOperation:(id)operation didReceiveResponse:(id)response;
-(void)run;
-(BOOL)copyAccountID:(id*)anId byAuthenticatingWithContext:(id)context returningError:(id*)error;
-(void)dealloc;
-(id)initWithDownloadIdentifiers:(id)downloadIdentifiers restoreReason:(id)reason;
@end

