/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <StoreServices/SSRestoreContentItem.h>

@class NSError, DownloadSessionProperties;

__attribute__((visibility("hidden")))
@interface RestoreDownloadItem : SSRestoreContentItem {
	long long _downloadIdentifier;
	DownloadSessionProperties* _downloadSessionProperties;
	NSError* _error;
}
@property(retain, nonatomic) NSError* error;
@property(copy, nonatomic) DownloadSessionProperties* downloadSessionProperties;
@property(readonly, assign, nonatomic) long long downloadIdentifier;
-(void)dealloc;
-(id)initWithDownloadIdentifier:(long long)downloadIdentifier;
@end

