/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSManagedObjectContext;

__attribute__((visibility("hidden")))
@interface RingtonePurchaseStore : NSObject {
	NSManagedObjectContext* _context;
	BOOL _ownsContext;
}
-(void)updateRingtonesForPurchases:(id)purchases withDownloads:(id)downloads;
-(id)ringtonesForAdamID:(unsigned long long)adamID transactionID:(id)anId;
-(void)removeRingtoneForAdamID:(unsigned long long)adamID transactionID:(id)anId;
-(void)removeRingtonesForPurchases:(id)purchases;
-(void)prunePurchasedRingtones;
-(void)finalizeRingtoneForAdamID:(unsigned long long)adamID transactionID:(id)anId ringtoneGUID:(id)guid;
-(void)addRingtonesForPurchases:(id)purchases;
-(void)dealloc;
-(id)initWithMangedObjectContext:(id)mangedObjectContext;
-(id)init;
@end

