/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import <CoreData/NSManagedObject.h>

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface RingtonePurchase : NSManagedObject {
}
@property(retain, nonatomic) NSString* transactionID;
@property(retain, nonatomic) NSNumber* shouldMakeDefaultTextTone;
@property(retain, nonatomic) NSNumber* shouldMakeDefault;
@property(retain, nonatomic) NSNumber* assignToPersonID;
@property(retain, nonatomic) NSString* assigneeToneStyle;
@property(retain, nonatomic) NSNumber* adamID;
+(id)entityFromContext:(id)context;
-(void)_makeDefaultWithIdentifier:(id)identifier defaultsKey:(CFStringRef)key;
-(void)_assignToPersonWithID:(int)anId withIdentifier:(id)identifier;
-(void)loadFromPurchase:(id)purchase;
-(void)applyUserActionWithIdentifier:(id)identifier;
@end

