/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class SSAuthenticationContext, NSSet, ClientIdentity;

__attribute__((visibility("hidden")))
@interface SetAutomaticDownloadKindsOperation : ISOperation {
	SSAuthenticationContext* _authenticationContext;
	ClientIdentity* _clientIdentity;
	NSSet* _downloadKinds;
	NSSet* _previousDownloadKinds;
	BOOL _runsOnlyIfKindsAreDirty;
}
@property(assign) BOOL runsOnlyIfKindsAreDirty;
@property(copy) NSSet* previousDownloadKinds;
@property(retain) ClientIdentity* clientIdentity;
@property(copy) SSAuthenticationContext* authenticationContext;
@property(readonly, assign) NSSet* downloadKinds;
-(void)_run;
-(BOOL)_postDownloadKinds:(id)kinds error:(id*)error;
-(BOOL)_isFatalError:(id)error;
-(id)_copyFilteredDownloadKinds;
-(id)uniqueKey;
-(BOOL)shouldFailAfterUniquePredecessorError:(id)error;
-(void)run;
-(void)dealloc;
-(id)initWithDownloadKinds:(id)downloadKinds;
@end

