/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSString, ClientIdentity;

__attribute__((visibility("hidden")))
@interface ShowServerPromptOperation : ISOperation {
	ClientIdentity* _clientIdentity;
	NSString* _promptIdentifier;
}
@property(retain) ClientIdentity* clientIdentity;
@property(readonly, assign) NSString* promptIdentifier;
-(BOOL)_promptNeedsDisplay;
-(id)_newStoreURLOperation:(id*)operation;
-(BOOL)_automaticDownloadsPromptNeedsDisplay;
-(void)run;
-(void)dealloc;
-(id)initWithPromptIdentifier:(id)promptIdentifier;
-(id)init;
@end

