/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class SignInResponse, SSAuthenticationContext;

__attribute__((visibility("hidden")))
@interface SignInPromptOperation : ISOperation {
	SSAuthenticationContext* _authenticationContext;
	SignInResponse* _response;
}
@property(readonly, assign) SignInResponse* signInResponse;
@property(readonly, assign) SSAuthenticationContext* authenticationContext;
-(id)_userNameTextField;
-(void)_setSignInResponseType:(int)responseType;
-(void)_setSignInResponse:(id)response;
-(int)_responseTypeByPromptingToCreateAccount:(id*)createAccount;
-(id)_passwordTextField;
-(id)_newSignInDialog;
-(id)_newCreateAccountDialog;
-(void)_enterCreateAccountFlow;
-(id)_copyResponseByPromptingForCredentials:(id*)credentials;
-(id)_activeUserName;
-(void)run;
-(void)dealloc;
-(id)initWithAuthenticationContext:(id)authenticationContext;
@end

