/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface SinfsArray : NSObject {
	NSArray* _sinfs;
}
@property(readonly, assign) NSArray* sinfs;
-(BOOL)_isRecognizedProperty:(id)property;
-(id)_copyValueForSINF:(id)sinf property:(id)property error:(id*)error;
-(id)copyValueForProperty:(id)property error:(id*)error;
-(id)copyValueForField:(int)field error:(id*)error;
-(void)dealloc;
-(id)initWithSINFs:(id)sinfs;
-(id)init;
@end

