/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSError, NSMutableDictionary, NSLock, NSString, NSMutableArray, NSArray;

__attribute__((visibility("hidden")))
@interface SoftwareUpdateStore : NSObject {
	NSString* _identifier;
	NSError* _lastError;
	BOOL _loadedFromServer;
	NSLock* _lock;
	NSArray* _softwareTypes;
	NSMutableDictionary* _stateCache;
	NSMutableArray* _updates;
}
@property(readonly, assign) NSString* storeIdentifier;
@property(copy) NSArray* softwareUpdates;
@property(readonly, assign) NSArray* softwareTypes;
@property(retain) NSError* lastError;
@property(assign, getter=isLoadedFromServer) BOOL loadedFromServer;
+(void)_postSoftwareUpdatesDidChange;
+(void)_performAutomaticSoftwareUpdateCheck;
+(void)setLastSoftwareUpdateCheckDate:(id)date;
+(void)performAutomaticSoftwareUpdateCheckIfNeeded;
+(void)performAutomaticSoftwareUpdateCheckForLaunch;
+(id)nextAutomaticSoftwareUpdateCheckDate;
+(double)automaticSoftwareUpdateCheckInterval;
+(id)softwareUpdateStoreForSoftwareTypes:(id)softwareTypes;
-(void)_setApplicationBadgeNumber:(int)number;
-(BOOL)_saveSoftwareUpdatesToCache;
-(BOOL)_removeUpdateForItemIdentifier:(unsigned long long)itemIdentifier;
-(id)_cacheFilePath;
-(void)_softwareMapChanged:(id)changed;
-(void)setState:(int)state forUpdatesWithItemIDs:(id)itemIDs;
-(void)resetApplicationBadge;
-(void)reloadApplicationBadge;
-(id)newCheckQueueResponse;
-(id)copyVisibleSoftwareUpdates;
-(void)dealloc;
-(id)init;
-(id)_initWithIdentifier:(id)identifier softwareTypes:(id)types;
@end

