/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"
#import "NSCopying.h"

@class NSData, NSString, NSDictionary;

__attribute__((visibility("hidden")))
@interface SoftwareProperties : NSObject <NSCopying> {
	NSData* _artworkData;
	NSDictionary* _iTunesMetadata;
	NSData* _newsstandArtworkData;
	NSString* _packagePath;
	NSData* _sinfData;
}
@property(copy, nonatomic) NSData* sinfData;
@property(copy, nonatomic) NSString* packagePath;
@property(copy, nonatomic) NSData* newsstandArtworkData;
@property(copy, nonatomic) NSDictionary* ITunesMetadata;
@property(copy, nonatomic) NSData* artworkData;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
@end

