/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import "SQLitePropertyPredicate.h"
#import "NSCopying.h"


__attribute__((visibility("hidden")))
@interface SQLiteComparisonPredicate : SQLitePropertyPredicate <NSCopying> {
	int _comparisonType;
	id _value;
}
@property(readonly, assign, nonatomic) id value;
@property(readonly, assign, nonatomic) int comparisonType;
+(id)predicateWithProperty:(id)property value:(id)value comparisonType:(int)type;
+(id)predicateWithProperty:(id)property equalToValue:(id)value;
-(id)_comparisonTypeString;
-(id)SQLForEntityClass:(Class)entityClass;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)bindToStatement:(sqlite3_stmt*)statement bindingIndex:(inout int*)index;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
@end

