/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import "SQLitePropertyPredicate.h"
#import "NSCopying.h"

@class NSString, NSArray, SQLiteQuery;

__attribute__((visibility("hidden")))
@interface SQLiteContainsPredicate : SQLitePropertyPredicate <NSCopying> {
	BOOL _negative;
	SQLiteQuery* _query;
	NSString* _queryProperty;
	id _values;
}
@property(readonly, assign, nonatomic) NSArray* values;
@property(readonly, assign, nonatomic) NSString* queryProperty;
@property(readonly, assign, nonatomic) SQLiteQuery* query;
@property(readonly, assign, nonatomic, getter=isNegative) BOOL negative;
+(id)doesNotContainPredicateWithProperty:(id)property values:(id)values;
+(id)containsPredicateWithProperty:(id)property query:(id)query queryProperty:(id)property3;
+(id)containsPredicateWithProperty:(id)property values:(id)values;
-(id)SQLForEntityClass:(Class)entityClass;
-(BOOL)isEqual:(id)equal;
-(void)bindToStatement:(sqlite3_stmt*)statement bindingIndex:(inout int*)index;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
@end

