/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"
#import "NSCopying.h"

@class SQLitePredicate, NSArray;

__attribute__((visibility("hidden")))
@interface SQLiteQueryDescriptor : NSObject <NSCopying> {
	Class _entityClass;
	int _limitCount;
	NSArray* _orderingDirections;
	NSArray* _orderingProperties;
	SQLitePredicate* _predicate;
	BOOL _returnsDistinctEntities;
}
@property(copy, nonatomic) SQLitePredicate* predicate;
@property(assign, nonatomic) BOOL returnsDistinctEntities;
@property(copy, nonatomic) NSArray* orderingProperties;
@property(copy, nonatomic) NSArray* orderingDirections;
@property(assign, nonatomic) int limitCount;
@property(assign, nonatomic) Class entityClass;
-(id)_newSelectSQLWithProperties:(id)properties columns:(id)columns;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
@end

