/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import "SQLitePredicate.h"
#import "NSCopying.h"

@class NSString, NSArray;

__attribute__((visibility("hidden")))
@interface SQLiteCompoundPredicate : SQLitePredicate <NSCopying> {
	NSString* _combinationOperation;
	NSArray* _predicates;
}
@property(readonly, assign, nonatomic) NSArray* predicates;
+(id)predicateWithProperty:(id)property values:(id)values comparisonType:(int)type;
+(id)predicateMatchingAnyPredicates:(id)predicates;
+(id)predicateMatchingAllPredicates:(id)predicates;
-(id)SQLJoinClausesForEntityClass:(Class)entityClass;
-(id)SQLForEntityClass:(Class)entityClass;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)bindToStatement:(sqlite3_stmt*)statement bindingIndex:(inout int*)index;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
@end

