/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import "SQLitePropertyPredicate.h"
#import "NSCopying.h"


__attribute__((visibility("hidden")))
@interface SQLiteNullPredicate : SQLitePropertyPredicate <NSCopying> {
	BOOL _matchesNull;
}
@property(readonly, assign, nonatomic) BOOL matchesNull;
+(id)isNullPredicateWithProperty:(id)property;
+(id)isNotNullPredicateWithProperty:(id)property;
-(id)SQLForEntityClass:(Class)entityClass;
-(BOOL)isEqual:(id)equal;
-(id)copyWithZone:(NSZone*)zone;
@end

