/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import "SQLitePredicate.h"
#import "NSCopying.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SQLitePropertyPredicate : SQLitePredicate <NSCopying> {
	NSString* _property;
}
@property(readonly, assign, nonatomic) NSString* property;
-(id)SQLJoinClausesForEntityClass:(Class)entityClass;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
@end

