/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import "NSCopying.h"
#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface SQLitePredicate : NSObject <NSCopying> {
}
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)SQLJoinClausesForEntityClass:(Class)entityClass;
-(id)SQLForEntityClass:(Class)entityClass;
-(void)bindToStatement:(sqlite3_stmt*)statement bindingIndex:(inout int*)index;
-(id)copyWithZone:(NSZone*)zone;
@end

