/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import <Foundation/NSObject.h>

@class SQLiteQueryDescriptor, ISSQLiteDatabase;

__attribute__((visibility("hidden")))
@interface SQLiteQuery : NSObject {
	ISSQLiteDatabase* _database;
	SQLiteQueryDescriptor* _descriptor;
}
@property(readonly, assign) int countOfEntities;
@property(readonly, assign) SQLiteQueryDescriptor* queryDescriptor;
@property(readonly, assign) ISSQLiteDatabase* database;
-(id)_newSelectSQLWithProperties:(id)properties;
-(void)enumeratePersistentIDsAndProperties:(id)properties usingBlock:(id)block;
-(void)enumeratePersistentIDsUsingBlock:(id)block;
-(BOOL)deleteAllEntities;
-(BOOL)createTemporaryTableWithName:(id)name properties:(id)properties;
-(id)copySelectSQLWithProperties:(id)properties;
-(id)copyEntityIdentifiers;
-(void)bindToSelectStatement:(sqlite3_stmt*)selectStatement bindingIndex:(inout int*)index;
-(void)dealloc;
-(id)initWithDatabase:(id)database descriptor:(id)descriptor;
@end

