/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "itunesstored-Structs.h"
#import <StoreServices/SSAccount.h>


@interface SSAccount (Daemon)
-(void)_saveString:(id)string toKeychainService:(CFStringRef)keychainService;
-(void)_removeValueFromKeychainForService:(CFStringRef)service;
-(id)_copyKeychainStringForService:(CFStringRef)service;
-(void)saveToKeychain;
-(void)removeFromKeychain;
-(BOOL)mergeValuesFromAccount:(id)account;
-(void)loadFromKeychain;
-(id)copyLockdownRepresentation;
-(void)commitToUserDefaults;
-(void)commitToLockdownInDomain:(CFStringRef)domain;
@end

