/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class SSAccount, NSArray;

@protocol SSAccountStore <NSObject>
@property(readonly, assign, getter=isExpired) BOOL expired;
@property(readonly, assign) NSArray* accounts;
@property(readonly, assign) SSAccount* activeLockerAccount;
@property(readonly, assign) SSAccount* activeAccount;
-(void)resetExpirationForTokenType:(int)tokenType;
-(void)resetExpiration;
-(BOOL)isExpiredForTokenType:(int)tokenType;
-(id)setActiveLockerAccount:(id)account;
-(id)setActiveAccount:(id)account;
-(id)addAccount:(id)account;
-(void)signOutAllAccounts;
-(void)signOutAccount:(id)account;
-(void)setAccountCredits:(id)credits forAccountWithUniqueIdentifier:(id)uniqueIdentifier;
-(id)accountWithUniqueIdentifier:(id)uniqueIdentifier reloadIfNecessary:(BOOL)necessary;
-(id)accountWithUniqueIdentifier:(id)uniqueIdentifier;
@end

