/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "StorePurchaseBatchOperationDelegate.h"
#import "RequestQueueOperation.h"

@class SSPurchaseRequest;

__attribute__((visibility("hidden")))
@interface StorePurchaseRequestOperation : RequestQueueOperation <StorePurchaseBatchOperationDelegate> {
	SSPurchaseRequest* _request;
}
-(void)_runPurchaseBatches:(id)batches;
-(id)_newPurchaseBatchOperationsWithPurchases:(id)purchases;
-(id)_copyPurchasesGroupedByAccountIdentifier:(id)identifier;
-(id)_cancelExistingPurchases;
-(void)_addRingtonePurchasesToDataStore:(id)dataStore;
-(BOOL)_addPlaceholdersForPurchaseBatches:(id)purchaseBatches;
-(void)storePurchaseBatchOperation:(id)operation didCompletePurchase:(id)purchase withError:(id)error;
-(void)run;
-(id)copyRequest;
-(void)dealloc;
-(id)initWithRequest:(id)request;
@end

