/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSArray, ClientIdentity;
@protocol StorePurchaseBatchOperationDelegate;

__attribute__((visibility("hidden")))
@interface StorePurchaseBatchOperation : ISOperation {
	ClientIdentity* _clientIdentity;
	BOOL _isBackgroundRequest;
	BOOL _needsAuthentication;
	NSArray* _purchases;
}
@property(assign) id<StorePurchaseBatchOperationDelegate> delegate;
@property(assign) BOOL needsAuthentication;
@property(assign, getter=isBackgroundRequest) BOOL backgroundRequest;
@property(retain) ClientIdentity* clientIdentity;
@property(readonly, assign) NSArray* purchases;
-(id)_userAgentForPurchases:(id)purchases;
-(void)_sendPurchaseFinished:(id)finished;
-(void)_sendPurchaseFailed:(id)failed withError:(id)error;
-(void)_sendError:(id)error forPurchase:(id)purchase;
-(void)_sendDelegatePurchaseCompleteWithPurchase:(id)purchase error:(id)error;
-(void)_runPurchaseOperations;
-(void)_notePurchasesFinished:(id)finished withDownloads:(id)downloads;
-(void)_notePurchasesFailed:(id)failed;
-(id)_copyRingtonePurchasesForPurchases:(id)purchases;
-(void)_checkUpdateQueueIfNecessary;
-(id)_clientIdentifierForPurchases:(id)purchases;
-(void)_cancelPurchasesWithError:(id)error;
-(BOOL)_authenticateReturningError:(id*)error;
-(void)run;
-(void)dealloc;
-(id)initWithPurchases:(id)purchases;
@end

