/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ISOperationDelegate.h"


@protocol StorePurchaseBatchOperationDelegate <ISOperationDelegate>
@optional
-(void)storePurchaseBatchOperation:(id)operation didCompletePurchase:(id)purchase withError:(id)error;
@end

