/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"
#import "NSCopying.h"

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface StoreDownloadQueueRequest : NSObject <NSCopying> {
	NSNumber* _accountIdentifier;
	NSString* _queueIdentifier;
}
@property(readonly, assign, nonatomic) NSString* queueCountURLBagKey;
@property(readonly, assign, nonatomic) NSString* queueContentsURLBagKey;
@property(copy, nonatomic) NSString* queueIdentifier;
@property(retain, nonatomic) NSNumber* accountIdentifier;
+(void)initialize;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
@end

