/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <iTunesStore/ISOperation.h>

@class NSNumber, NSOrderedSet, NSString, SSPurchase, ClientIdentity;

__attribute__((visibility("hidden")))
@interface StorePurchaseOperation : ISOperation {
	NSNumber* _accountID;
	ClientIdentity* _clientIdentity;
	BOOL _displayedErrorDialog;
	NSOrderedSet* _downloads;
	BOOL _isBackgroundPurchase;
	BOOL _needsAuthentication;
	BOOL _partOfBatchPurchase;
	SSPurchase* _purchase;
	BOOL _shouldCancelPurchaseBatch;
	BOOL _triggeredQueueCheck;
	NSString* _urlBagKey;
}
@property(assign) BOOL triggeredQueueCheck;
@property(assign) BOOL shouldCancelPurchaseBatch;
@property(retain) NSOrderedSet* downloads;
@property(assign) BOOL displayedErrorDialog;
@property(retain) NSString* urlBagKey;
@property(assign, getter=isPartOfBatchPurchase) BOOL partOfBatchPurchase;
@property(assign) BOOL needsAuthentication;
@property(assign, getter=isBackgroundPurchase) BOOL backgroundPurchase;
@property(retain) ClientIdentity* clientIdentity;
@property(readonly, assign) SSPurchase* purchase;
-(void)_runPurchaseOperation;
-(int)_responseTypeForResponse:(id)response;
-(void)_handlePreOrderResponse:(id)response;
-(void)_handleDefaultResponse:(id)response;
-(void)run:(BOOL)run;
-(void)run;
-(id)authenticatedAccountDSID;
-(void)dealloc;
-(id)initWithPurchase:(id)purchase;
-(id)init;
@end

