/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"

@class NSError, NSData, NSNumber, NSOrderedSet, NSArray, NSDictionary, NSMutableOrderedSet;

__attribute__((visibility("hidden")))
@interface StoreDownloadQueueResponse : NSObject {
	dispatch_queue_s* _dispatchQueue;
	NSMutableOrderedSet* _downloads;
	NSError* _error;
	NSDictionary* _itemErrors;
	NSData* _keybag;
	NSArray* _rangesToLoad;
	BOOL _shouldCancelPurchaseBatch;
	BOOL _triggeredQueueCheck;
	NSNumber* _userIdentifier;
}
@property(readonly, assign) NSNumber* userIdentifier;
@property(assign) BOOL triggeredQueueCheck;
@property(assign) BOOL shouldCancelPurchaseBatch;
@property(readonly, assign) NSArray* rangesToLoad;
@property(readonly, assign) NSData* keybag;
@property(retain) NSError* error;
@property(readonly, assign) NSOrderedSet* downloads;
-(id)_errorWithFailureType:(id)failureType customerMessage:(id)message;
-(id)errorForItemIdentifier:(id)itemIdentifier;
-(void)dealloc;
-(id)initWithError:(id)error userIdentifier:(id)identifier;
-(id)initWithDictionary:(id)dictionary userIdentifier:(id)identifier;
-(id)init;
-(id)_initStoreDownloadQueueResponse;
@end

