/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <StoreServices/SSDownloadMetadata.h>

@class NSNumber;

__attribute__((visibility("hidden")))
@interface StoreDownload : SSDownloadMetadata {
}
@property(readonly, assign) NSNumber* redownloadedStatus;
@property(readonly, assign) NSNumber* matchedStatus;
-(id)_copyPinfValueWithField:(int)field;
-(id)newDownloadProperties;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)description;
-(BOOL)writeToFile:(id)file options:(unsigned)options error:(id*)error;
-(id)initWithDownload:(id)download;
-(id)initWithContentsOfFile:(id)file;
@end

