/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"

@class NSMutableSet, NSSet, NSNumber, ISOperationQueue, LoadDownloadQueueOperation, NSMutableOrderedSet;

__attribute__((visibility("hidden")))
@interface StoreDownloadQueue : NSObject {
	NSMutableOrderedSet* _activeRestoreIDs;
	dispatch_queue_s* _dispatchQueue;
	NSNumber* _lastCheckedAccountID;
	LoadDownloadQueueOperation* _loadAutomaticDownloadQueueOperation;
	ISOperationQueue* _operationQueue;
	ISOperationQueue* _restoreOperationQueue;
	BOOL _restoreItemsUnavailableScheduled;
	NSMutableSet* _storeQueueRequests;
	NSMutableOrderedSet* _trackedPurchaseDownloadIDs;
}
@property(copy, nonatomic) NSSet* automaticDownloadKinds;
@property(readonly, assign) NSSet* downloadKindsBeingChecked;
+(id)sharedDownloadQueue;
-(void)_showRestoreItemsUnavailableIfNecessary;
-(void)_setLastCheckedAccountID:(id)anId;
-(id)_restorableDownloadsQueryInDatabase:(id)database;
-(id)_newSetAutomaticDownloadKindsOperationWithDownloadKinds:(id)downloadKinds;
-(id)_newQueueRequestsForDatabase;
-(id)_newOperationByCommitingAutomaticDownloadKinds:(id)kinds;
-(id)_newLoadQueueOperationForQueueRequest:(id)queueRequest;
-(id)_newCheckQueueOperationForQueueRequest:(id)queueRequest;
-(BOOL)_mergeStoreDownloads:(id)downloads withDownloadQuery:(id)downloadQuery accountID:(id)anId changeInfo:(DownloadChangeInfo*)info;
-(void)_mergeDownloads:(id)downloads forQueueRequest:(id)queueRequest;
-(id)_downloadQueryWithQueueRequest:(id)queueRequest;
-(id)_databaseDownloadForStoreDownload:(id)storeDownload inDatabase:(id)database;
-(id)_copyQueueRequestsWithAccountID:(id)accountID;
-(id)_automaticDownloadsQueryWithDatabase:(id)database accountID:(id)anId;
-(void)_accountStoreChangedNotification:(id)notification;
-(void)_accountAuthenticatedNotification:(id)notification;
-(void)synchronizeAutomaticDownloadKinds;
-(void)scheduleRestoreItemsUnavailableDialog;
-(void)setAutomaticDownloadKinds:(id)kinds identity:(id)identity;
-(void)restoreDownloadsWithIdentifiers:(id)identifiers reason:(id)reason;
-(void)restoreAllRestorableDownloadsWithReason:(id)reason;
-(void)reconcileSoftwareDownloads:(id)downloads fromITunesStore:(BOOL)itunesStore withDatabase:(id)database changeInfo:(DownloadChangeInfo*)info;
-(void)pruneOrphanedPurchases;
-(id)placeholderDownloadForPurchase:(id)purchase database:(id)database;
-(void)mergeQueueResponse:(id)response forPurchase:(id)purchase;
-(void)endTrackingPurchaseOperationWithDownloadIDs:(id)downloadIDs;
-(void)commitAutomaticDownloadKinds:(id)kinds markAsDirty:(BOOL)dirty;
-(BOOL)checkQueuesWithReason:(id)reason;
-(void)checkAutomaticDownloadQueue;
-(BOOL)cancelAllRedownloads;
-(void)beginTrackingPurchaseOperationWithDownloadIDs:(id)downloadIDs;
-(void)dealloc;
-(id)init;
@end

