/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface UserNotificationCenter : NSObject {
	dispatch_queue_s* _dispatchQueue;
	NSMutableArray* _userNotifications;
}
+(id)defaultCenter;
-(void)_finishUserNotification:(CFUserNotificationRef)notification withResponseFlags:(unsigned long)responseFlags;
-(void)updateUserNotification:(id)notification withUserNotification:(id)userNotification;
-(void)updateUserNotification:(id)notification withDictionary:(CFDictionaryRef)dictionary options:(unsigned long)options;
-(void)updateUserNotification:(id)notification withDialog:(id)dialog;
-(id)showUserNotification:(CFDictionaryRef)notification withOptions:(unsigned long)options completionBlock:(id)block;
-(id)showUserNotification:(id)notification withCompletionBlock:(id)completionBlock;
-(id)showDialog:(id)dialog withCompletionBlock:(id)completionBlock;
-(void)cancelUserNotifications:(id)notifications;
-(void)cancelUserNotification:(id)notification;
-(void)dealloc;
-(id)init;
@end

