/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "itunesstored-Structs.h"

@class SSXPCConnection, NSMutableDictionary, NSString, NSDictionary, NSMutableIndexSet;

__attribute__((visibility("hidden")))
@interface XPCClient : NSObject {
	unsigned _applicationState;
	NSMutableDictionary* _backgroundTasks;
	NSString* _clientIdentifier;
	int _clientType;
	dispatch_queue_s* _dispatchQueue;
	NSDictionary* _entitlements;
	NSMutableIndexSet* _inflightMessages;
	xpc_connection_s* _inputConnection;
	BOOL _legacyEntitlements;
	SSXPCConnection* _outputConnection;
	int _pid;
}
@property(readonly, assign) SSXPCConnection* outputConnection;
@property(readonly, assign) int processIdentifier;
@property(readonly, assign, getter=isNewsstandApp) BOOL newsstandApp;
@property(readonly, assign) BOOL hasEntitlements;
@property(readonly, assign) int clientType;
@property(readonly, assign) NSString* clientIdentifier;
@property(readonly, assign) BOOL canReceiveMessages;
@property(readonly, assign) unsigned applicationState;
-(void)_invalidateBackgroundTaskAssertion:(SBSProcessAssertionRef)assertion;
-(int)_clientType;
-(unsigned)_applicationState;
-(void)_applicationStateChanged:(id)changed;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)description;
-(id)valueForEntitlement:(id)entitlement;
-(void)setOutputConnectionWithConnection:(xpc_connection_s*)connection;
-(void)sendCoalescedMessageWithIdentifier:(unsigned)identifier;
-(void)endBackgroundTaskWithIdentifier:(id)identifier;
-(xpc_connection_s*)copyInputConnection;
-(id)copyApplicationBackgroundModes;
-(id)beginBackgroundTaskWithReason:(unsigned)reason expirationBlock:(id)block;
-(void)dealloc;
-(id)initWithInputConnection:(xpc_connection_s*)inputConnection;
-(id)init;
@end

